import { Field } from "./types";

export const fields: Field[] = [
  {
    id: "nlp",
    titleKo: "자연어처리",
    titleEn: "Natural Language Processing",
    descriptionKo: "언어모델, 번역, QA, 요약, 토크나이저 등 텍스트 이해와 생성에 관한 연구",
    descriptionEn: "Research on text understanding and generation",
    color: "violet",
    years: [],
  },
  {
    id: "cv",
    titleKo: "컴퓨터 비전",
    titleEn: "Computer Vision",
    descriptionKo: "분류, 검출, 분할, 3D 비전, 비디오 분석 등 시각 정보 처리 연구",
    descriptionEn: "Research on visual information processing",
    color: "orange",
    years: [],
  },
  {
    id: "generative",
    titleKo: "생성 모델",
    titleEn: "Generative Models",
    descriptionKo: "GAN, VAE, Diffusion, Flow 등 데이터 생성에 관한 연구",
    descriptionEn: "Research on data generation models",
    color: "cyan",
    years: [],
  },
  {
    id: "rl",
    titleKo: "강화학습",
    titleEn: "Reinforcement Learning",
    descriptionKo: "MDP, 정책 경사, Actor-Critic, MARL, 게임 AI 등",
    descriptionEn: "Research on learning from interaction and rewards",
    color: "rose",
    years: [],
  },
  {
    id: "llm",
    titleKo: "대규모 언어모델",
    titleEn: "Large Language Models",
    descriptionKo: "스케일링, RLHF, 프롬프팅, RAG, 에이전트, 추론 등",
    descriptionEn: "Research on scaling and capabilities of language models",
    color: "amber",
    years: [],
  },
  {
    id: "multimodal",
    titleKo: "멀티모달",
    titleEn: "Multimodal AI",
    descriptionKo: "비전-언어, 오디오-텍스트, 통합 모델 연구",
    descriptionEn: "Research on multi-modal understanding and generation",
    color: "teal",
    years: [],
  },
  {
    id: "graph",
    titleKo: "그래프 ML",
    titleEn: "Graph Machine Learning",
    descriptionKo: "GNN, Knowledge Graph, 분자 그래프 등 그래프 구조 학습",
    descriptionEn: "Research on learning from graph-structured data",
    color: "indigo",
    years: [],
  },
  {
    id: "robotics",
    titleKo: "로보틱스",
    titleEn: "Robotics & Embodied AI",
    descriptionKo: "조작, 내비게이션, Sim2Real, 체화 에이전트 연구",
    descriptionEn: "Research on robotic manipulation, navigation, and embodied agents",
    color: "red",
    years: [],
  },
  {
    id: "safety",
    titleKo: "AI 안전성·정렬",
    titleEn: "AI Safety & Alignment",
    descriptionKo: "정렬, 해석 가능성, 레드팀, 거버넌스 연구",
    descriptionEn: "Research on making AI systems safe and aligned",
    color: "fuchsia",
    years: [],
  },
  {
    id: "optimization",
    titleKo: "최적화·학습이론",
    titleEn: "Optimization & Learning Theory",
    descriptionKo: "SGD, Adam, 수렴 이론, 일반화, 손실 함수 연구",
    descriptionEn: "Research on optimization methods and learning theory",
    color: "blue",
    years: [],
  },
  {
    id: "representation",
    titleKo: "표현 학습",
    titleEn: "Representation Learning",
    descriptionKo: "자기지도학습, 대조학습, 사전학습, 전이학습 연구",
    descriptionEn: "Research on learning useful representations",
    color: "emerald",
    years: [],
  },
  {
    id: "science",
    titleKo: "AI for Science",
    titleEn: "AI for Science",
    descriptionKo: "단백질 접힘, 신약, 기후, 수학 증명 등 과학 연구에 AI 적용",
    descriptionEn: "Applying AI to scientific research",
    color: "lime",
    years: [],
  },
  {
    id: "efficient",
    titleKo: "경량화·효율화",
    titleEn: "Efficient AI",
    descriptionKo: "양자화, 프루닝, 증류, NAS, 추론 최적화 연구",
    descriptionEn: "Research on making AI models smaller and faster",
    color: "sky",
    years: [],
  },
  {
    id: "world-models",
    titleKo: "월드 모델",
    titleEn: "World Models",
    descriptionKo: "비디오 예측, 시뮬레이션, 내부 세계 모델 연구",
    descriptionEn: "Research on learning world representations",
    color: "purple",
    years: [],
  },
  {
    id: "audio",
    titleKo: "음성·오디오",
    titleEn: "Audio & Speech",
    descriptionKo: "ASR, TTS, 음악 생성, 오디오 이해 연구",
    descriptionEn: "Research on audio and speech processing",
    color: "slate",
    years: [],
  },
];
