import type { Paper } from "./types";

export const newPapers: Record<string, Paper[]> = {
  "rl": [
    {
      id: "a3c",
      title: "Asynchronous Methods for Deep Reinforcement Learning",
      titleKo: "딥 강화학습을 위한 비동기 방법",
      authors: ["Volodymyr Mnih", "Adrià Puigdomènech Badia", "et al."],
      year: 2016,
      venue: "ICML 2016",
      venueType: "icml",
      arxivUrl: "https://arxiv.org/abs/1602.01783",
      tags: [],
      status: "complete",
      citations: "12,000+",
    },
    {
      id: "alphazero",
      title: "Mastering Chess and Shogi by Self-Play with a General Reinforcement Learning Algorithm",
      titleKo: "범용 강화학습 알고리즘의 자기대국으로 체스와 쇼기 마스터하기",
      authors: ["David Silver", "Thomas Hubert", "Julian Schrittwieser", "et al."],
      year: 2017,
      venue: "arXiv",
      venueType: "arxiv",
      arxivUrl: "https://arxiv.org/abs/1712.01815",
      tags: [],
      status: "complete",
      citations: "5,000+",
    },
    {
      id: "sac",
      title: "Soft Actor-Critic: Off-Policy Maximum Entropy Deep Reinforcement Learning with a Stochastic Actor",
      titleKo: "소프트 액터-크리틱: 확률적 액터를 이용한 오프폴리시 최대 엔트로피 딥 강화학습",
      authors: ["Tuomas Haarnoja", "Aurick Zhou", "Pieter Abbeel", "Sergey Levine"],
      year: 2018,
      venue: "ICML 2018",
      venueType: "icml",
      arxivUrl: "https://arxiv.org/abs/1801.01290",
      tags: [],
      status: "complete",
      citations: "8,000+",
    },
    {
      id: "alphastar",
      title: "Grandmaster level in StarCraft II using multi-agent reinforcement learning",
      titleKo: "다중 에이전트 강화학습을 이용한 스타크래프트 II 그랜드마스터 달성",
      authors: ["Oriol Vinyals", "Igor Babuschkin", "et al."],
      year: 2019,
      venue: "Nature",
      venueType: "nature",
      conferenceUrl: "https://doi.org/10.1038/s41586-019-1724-z",
      tags: [],
      status: "complete",
      citations: "3,000+",
    },
    {
      id: "decision-transformer",
      title: "Decision Transformer: Reinforcement Learning via Sequence Modeling",
      titleKo: "결정 트랜스포머: 시퀀스 모델링을 통한 강화학습",
      authors: ["Lili Chen", "Kevin Lu", "Aravind Rajeswaran", "et al."],
      year: 2021,
      venue: "NeurIPS 2021",
      venueType: "neurips",
      arxivUrl: "https://arxiv.org/abs/2106.01345",
      tags: [],
      status: "complete",
      citations: "2,500+",
    },
    {
      id: "dreamerv3",
      title: "Mastering Diverse Domains through World Models",
      titleKo: "월드 모델을 통한 다양한 도메인 마스터하기",
      authors: ["Danijar Hafner", "Jurgis Pasukonis", "Jimmy Ba", "Timothy Lillicrap"],
      year: 2023,
      venue: "arXiv",
      venueType: "arxiv",
      arxivUrl: "https://arxiv.org/abs/2301.04104",
      tags: [],
      status: "complete",
      citations: "1,000+",
    },
  ],
  "robotics": [
    {
      id: "bcz",
      title: "BC-Z: Zero-Shot Task Generalization with Robotic Imitation Learning",
      titleKo: "BC-Z: 로봇 모방학습을 이용한 제로샷 태스크 일반화",
      authors: ["Eric Jang", "Alex Irpan", "Mohi Khansari", "et al."],
      year: 2021,
      venue: "CoRL 2021",
      venueType: "other",
      arxivUrl: "https://arxiv.org/abs/2202.02005",
      tags: [],
      status: "complete",
      citations: "300+",
    },
    {
      id: "cliport",
      title: "CLIPort: What and Where Pathways for Robotic Manipulation",
      titleKo: "CLIPort: 로봇 조작을 위한 What and Where 경로",
      authors: ["Mohit Shridhar", "Lucas Manuelli", "Dieter Fox"],
      year: 2021,
      venue: "CoRL 2021",
      venueType: "other",
      arxivUrl: "https://arxiv.org/abs/2109.12098",
      tags: [],
      status: "complete",
      citations: "500+",
    },
    {
      id: "rt1",
      title: "RT-1: Robotics Transformer for Real-World Control at Scale",
      titleKo: "RT-1: 대규모 실세계 제어를 위한 로보틱스 트랜스포머",
      authors: ["Anthony Brohan", "Noah Brown", "Justice Carbajal", "et al."],
      year: 2022,
      venue: "RSS 2023",
      venueType: "other",
      arxivUrl: "https://arxiv.org/abs/2212.06817",
      tags: [],
      status: "complete",
      citations: "800+",
    },
    {
      id: "inner-monologue",
      title: "Inner Monologue: Embodied Reasoning through Planning with Language Models",
      titleKo: "내면 독백: 언어 모델을 이용한 체화된 추론과 계획",
      authors: ["Wenlong Huang", "Fei Xia", "Ted Xiao", "et al."],
      year: 2022,
      venue: "CoRL 2022",
      venueType: "other",
      arxivUrl: "https://arxiv.org/abs/2207.05608",
      tags: [],
      status: "complete",
      citations: "600+",
    },
    {
      id: "gato",
      title: "A Generalist Agent",
      titleKo: "범용 에이전트",
      authors: ["Scott Reed", "Konrad Żołna", "Emilio Parisotto", "et al."],
      year: 2022,
      venue: "TMLR 2022",
      venueType: "other",
      arxivUrl: "https://arxiv.org/abs/2205.06175",
      tags: [],
      status: "complete",
      citations: "1,500+",
    },
    {
      id: "voxposer",
      title: "VoxPoser: Composable 3D Value Maps for Robotic Manipulation with Language Models",
      titleKo: "VoxPoser: 언어 모델을 이용한 로봇 조작용 합성형 3D 가치 맵",
      authors: ["Wenlong Huang", "Chen Wang", "Ruohan Zhang", "et al."],
      year: 2023,
      venue: "CoRL 2023",
      venueType: "other",
      arxivUrl: "https://arxiv.org/abs/2307.05973",
      tags: [],
      status: "complete",
      citations: "300+",
    },
    {
      id: "aloha",
      title: "Learning Fine-Grained Bimanual Manipulation with Low-Cost Hardware",
      titleKo: "저비용 하드웨어를 이용한 정밀 양손 조작 학습",
      authors: ["Tony Z. Zhao", "Vikash Kumar", "Sergey Levine", "Chelsea Finn"],
      year: 2023,
      venue: "RSS 2023",
      venueType: "other",
      arxivUrl: "https://arxiv.org/abs/2304.13705",
      tags: [],
      status: "complete",
      citations: "400+",
    },
    {
      id: "mobile-aloha",
      title: "Mobile ALOHA: Learning Bimanual Mobile Manipulation with Low-Cost Whole-Body Teleoperation",
      titleKo: "Mobile ALOHA: 저비용 전신 원격조작을 이용한 양손 이동 조작 학습",
      authors: ["Zipeng Fu", "Tony Z. Zhao", "Chelsea Finn"],
      year: 2024,
      venue: "arXiv",
      venueType: "arxiv",
      arxivUrl: "https://arxiv.org/abs/2401.02117",
      tags: [],
      status: "complete",
      citations: "200+",
    },
  ],
  "world-models": [
    {
      id: "dreamerv1",
      title: "Dream to Control: Learning Behaviors by Latent Imagination",
      titleKo: "꿈꾸며 제어하기: 잠재 상상을 통한 행동 학습",
      authors: ["Danijar Hafner", "Timothy Lillicrap", "Jimmy Ba", "Mohammad Norouzi"],
      year: 2020,
      venue: "ICLR 2020",
      venueType: "iclr",
      arxivUrl: "https://arxiv.org/abs/1912.01603",
      tags: [],
      status: "complete",
      citations: "1,500+",
    },
    {
      id: "dreamerv2",
      title: "Mastering Atari with Discrete World Models",
      titleKo: "이산 월드 모델로 Atari 마스터하기",
      authors: ["Danijar Hafner", "Timothy Lillicrap", "Mohammad Norouzi", "Jimmy Ba"],
      year: 2021,
      venue: "ICLR 2021",
      venueType: "iclr",
      arxivUrl: "https://arxiv.org/abs/2010.02193",
      tags: [],
      status: "complete",
      citations: "1,200+",
    },
    {
      id: "jepa",
      title: "A Path Towards Autonomous Machine Intelligence",
      titleKo: "자율적 기계 지능으로의 경로",
      authors: ["Yann LeCun"],
      year: 2022,
      venue: "OpenReview",
      venueType: "other",
      conferenceUrl: "https://openreview.net/pdf?id=BZ5a1r-kVsf",
      tags: [],
      status: "complete",
      citations: "1,000+",
    },
    {
      id: "iris",
      title: "Transformers are Sample-Efficient World Learners",
      titleKo: "트랜스포머는 샘플 효율적인 월드 학습기이다",
      authors: ["Vincent Micheli", "Eloi Alonso", "François Fleuret"],
      year: 2023,
      venue: "ICLR 2023",
      venueType: "iclr",
      arxivUrl: "https://arxiv.org/abs/2209.00588",
      tags: [],
      status: "complete",
      citations: "300+",
    },
    {
      id: "unisim",
      title: "UniSim: Learning Interactive Real-World Simulators",
      titleKo: "UniSim: 인터랙티브 실세계 시뮬레이터 학습",
      authors: ["Mengjiao Yang", "Yilun Du", "Kamyar Ghasemipour", "et al."],
      year: 2023,
      venue: "ICLR 2024",
      venueType: "iclr",
      arxivUrl: "https://arxiv.org/abs/2310.06114",
      tags: [],
      status: "complete",
      citations: "200+",
    },
    {
      id: "gamenngen",
      title: "GameNGen: Diffusion Models Are Real-Time Game Engines",
      titleKo: "GameNGen: 확산 모델은 실시간 게임 엔진이다",
      authors: ["Dani Valevski", "Yaniv Leviathan", "Moab Arar", "Shlomi Fruchter"],
      year: 2024,
      venue: "arXiv",
      venueType: "arxiv",
      arxivUrl: "https://arxiv.org/abs/2408.14837",
      tags: [],
      status: "complete",
      citations: "100+",
    },
  ],
};
