import { Field } from "./types";

export const fields: Field[] = [
  {
    id: "nlp",
    titleKo: "자연어처리",
    titleEn: "Natural Language Processing",
    descriptionKo: "언어모델, 번역, QA, 요약, 토크나이저 등 텍스트 이해와 생성에 관한 연구",
    descriptionEn: "Research on text understanding and generation",
    color: "violet",
    years: [
      {
        year: 2013,
        papers: [
          {
            id: "word2vec",
            title: "Efficient Estimation of Word Representations in Vector Space",
            titleKo: "벡터 공간에서의 효율적 단어 표현 추정",
            authors: ["Tomas Mikolov","Kai Chen","Greg Corrado","Jeffrey Dean"],
            year: 2013,
            venue: "ICLR 2013 Workshop",
            venueType: "iclr",
            arxivUrl: "https://arxiv.org/abs/1301.3781",
            tags: [],
            status: "complete",
            citations: "40,000+",
          },
        ],
      },
      {
        year: 2014,
        papers: [
          {
            id: "glove",
            title: "GloVe: Global Vectors for Word Representation",
            titleKo: "GloVe: 단어 표현을 위한 글로벌 벡터",
            authors: ["Jeffrey Pennington","Richard Socher","Christopher Manning"],
            year: 2014,
            venue: "EMNLP 2014",
            venueType: "emnlp",
            arxivUrl: "https://nlp.stanford.edu/pubs/glove.pdf",
            tags: [],
            status: "complete",
            citations: "30,000+",
          },
        ],
      },
      {
        year: 2018,
        papers: [
          {
            id: "elmo",
            title: "Deep contextualized word representations",
            titleKo: "심층 문맥화 단어 표현",
            authors: ["Matthew E. Peters","Mark Neumann","Mohit Iyyer","et al."],
            year: 2018,
            venue: "NAACL 2018",
            venueType: "naacl",
            award: "best-paper",
            arxivUrl: "https://arxiv.org/abs/1802.05365",
            tags: [],
            status: "complete",
            citations: "15,000+",
          },
        ],
      },
      {
        year: 2019,
        papers: [
          {
            id: "t5",
            title: "Exploring the Limits of Transfer Learning with a Unified Text-to-Text Transformer",
            titleKo: "통합 텍스트-투-텍스트 트랜스포머를 통한 전이학습의 한계 탐구",
            authors: ["Colin Raffel","Noam Shazeer","Adam Roberts","et al."],
            year: 2019,
            venue: "JMLR 2020",
            venueType: "jmlr",
            arxivUrl: "https://arxiv.org/abs/1910.10683",
            tags: [],
            status: "complete",
            citations: "18,000+",
          },
          {
            id: "xlnet",
            title: "XLNet: Generalized Autoregressive Pretraining for Language Understanding",
            titleKo: "XLNet: 언어 이해를 위한 일반화된 자기회귀 사전학습",
            authors: ["Zhilin Yang","Zihang Dai","Yiming Yang","et al."],
            year: 2019,
            venue: "NeurIPS 2019",
            venueType: "neurips",
            arxivUrl: "https://arxiv.org/abs/1906.08237",
            tags: [],
            status: "complete",
            citations: "8,000+",
          },
          {
            id: "roberta",
            title: "RoBERTa: A Robustly Optimized BERT Pretraining Approach",
            titleKo: "RoBERTa: 강건하게 최적화된 BERT 사전학습 접근법",
            authors: ["Yinhan Liu","Myle Ott","Naman Goyal","et al."],
            year: 2019,
            venue: "arXiv",
            venueType: "arxiv",
            arxivUrl: "https://arxiv.org/abs/1907.11692",
            tags: [],
            status: "complete",
            citations: "18,000+",
          },
        ],
      },
      {
        year: 2020,
        papers: [
          {
            id: "bart",
            title: "BART: Denoising Sequence-to-Sequence Pre-training for Natural Language Generation, Translation, and Comprehension",
            titleKo: "BART: 자연어 생성, 번역, 이해를 위한 디노이징 시퀀스-투-시퀀스 사전학습",
            authors: ["Mike Lewis","Yinhan Liu","Naman Goyal","et al."],
            year: 2020,
            venue: "ACL 2020",
            venueType: "acl",
            arxivUrl: "https://arxiv.org/abs/1910.13461",
            tags: [],
            status: "complete",
            citations: "10,000+",
          },
          {
            id: "deberta",
            title: "DeBERTa: Decoding-enhanced BERT with Disentangled Attention",
            titleKo: "DeBERTa: 분리된 어텐션을 활용한 디코딩 강화 BERT",
            authors: ["Pengcheng He","Xiaodong Liu","Jianfeng Gao","Weizhu Chen"],
            year: 2020,
            venue: "ICLR 2021",
            venueType: "iclr",
            arxivUrl: "https://arxiv.org/abs/2006.03654",
            tags: [],
            status: "complete",
            citations: "4,000+",
          },
        ],
      },
      {
        year: 2022,
        papers: [
          {
            id: "instructgpt",
            title: "Training language models to follow instructions with human feedback",
            titleKo: "인간 피드백으로 지시를 따르도록 언어 모델 학습",
            authors: ["Long Ouyang","Jeff Wu","Xu Jiang","et al."],
            year: 2022,
            venue: "NeurIPS 2022",
            venueType: "neurips",
            arxivUrl: "https://arxiv.org/abs/2203.02155",
            tags: [],
            status: "complete",
            citations: "8,000+",
          },
          {
            id: "flan-t5",
            title: "Scaling Instruction-Finetuned Language Models",
            titleKo: "지시 미세조정 언어 모델의 스케일링",
            authors: ["Hyung Won Chung","Le Hou","Shayne Longpre","et al."],
            year: 2022,
            venue: "arXiv",
            venueType: "arxiv",
            arxivUrl: "https://arxiv.org/abs/2210.11416",
            tags: [],
            status: "complete",
            citations: "5,000+",
          },
        ],
      },
    ],
  },
  {
    id: "cv",
    titleKo: "컴퓨터 비전",
    titleEn: "Computer Vision",
    descriptionKo: "분류, 검출, 분할, 3D 비전, 비디오 분석 등 시각 정보 처리 연구",
    descriptionEn: "Research on visual information processing",
    color: "orange",
    years: [
      {
        year: 2015,
        papers: [
          {
            id: "yolo",
            title: "You Only Look Once: Unified, Real-Time Object Detection",
            titleKo: "한 번만 보면 된다: 통합 실시간 객체 검출",
            authors: ["Joseph Redmon","Santosh Divvala","Ross Girshick","Ali Farhadi"],
            year: 2015,
            venue: "CVPR 2016",
            venueType: "cvpr",
            arxivUrl: "https://arxiv.org/abs/1506.02640",
            tags: [],
            status: "complete",
            citations: "35,000+",
          },
          {
            id: "unet",
            title: "U-Net: Convolutional Networks for Biomedical Image Segmentation",
            titleKo: "U-Net: 의료 영상 분할을 위한 합성곱 네트워크",
            authors: ["Olaf Ronneberger","Philipp Fischer","Thomas Brox"],
            year: 2015,
            venue: "MICCAI 2015",
            venueType: "other",
            arxivUrl: "https://arxiv.org/abs/1505.04597",
            tags: [],
            status: "complete",
            citations: "70,000+",
          },
          {
            id: "inception",
            title: "Going Deeper with Convolutions",
            titleKo: "더 깊은 합성곱으로: 인셉션 네트워크",
            authors: ["Christian Szegedy","Wei Liu","Yangqing Jia","et al."],
            year: 2015,
            venue: "CVPR 2015",
            venueType: "cvpr",
            award: "best-paper",
            arxivUrl: "https://arxiv.org/abs/1409.4842",
            tags: [],
            status: "complete",
            citations: "40,000+",
          },
        ],
      },
      {
        year: 2017,
        papers: [
          {
            id: "mask-rcnn",
            title: "Mask R-CNN",
            titleKo: "Mask R-CNN",
            authors: ["Kaiming He","Georgia Gkioxari","Piotr Dollár","Ross Girshick"],
            year: 2017,
            venue: "ICCV 2017",
            venueType: "iccv",
            award: "best-paper",
            arxivUrl: "https://arxiv.org/abs/1703.06870",
            tags: [],
            status: "complete",
            citations: "20,000+",
          },
          {
            id: "fpn",
            title: "Feature Pyramid Networks for Object Detection",
            titleKo: "객체 검출을 위한 특징 피라미드 네트워크",
            authors: ["Tsung-Yi Lin","Piotr Dollár","Ross Girshick","et al."],
            year: 2017,
            venue: "CVPR 2017",
            venueType: "cvpr",
            arxivUrl: "https://arxiv.org/abs/1612.03144",
            tags: [],
            status: "complete",
            citations: "18,000+",
          },
        ],
      },
      {
        year: 2019,
        papers: [
          {
            id: "efficientnet",
            title: "EfficientNet: Rethinking Model Scaling for Convolutional Neural Networks",
            titleKo: "EfficientNet: 합성곱 신경망의 모델 스케일링 재고",
            authors: ["Mingxing Tan","Quoc V. Le"],
            year: 2019,
            venue: "ICML 2019",
            venueType: "icml",
            arxivUrl: "https://arxiv.org/abs/1905.11946",
            tags: [],
            status: "complete",
            citations: "20,000+",
          },
        ],
      },
      {
        year: 2020,
        papers: [
          {
            id: "detr",
            title: "End-to-End Object Detection with Transformers",
            titleKo: "트랜스포머를 이용한 엔드투엔드 객체 검출",
            authors: ["Nicolas Carion","Francisco Massa","Gabriel Synnaeve","et al."],
            year: 2020,
            venue: "ECCV 2020",
            venueType: "eccv",
            arxivUrl: "https://arxiv.org/abs/2005.12872",
            tags: [],
            status: "complete",
            citations: "10,000+",
          },
        ],
      },
      {
        year: 2021,
        papers: [
          {
            id: "swin-transformer",
            title: "Swin Transformer: Hierarchical Vision Transformer using Shifted Windows",
            titleKo: "Swin Transformer: 이동 윈도우를 이용한 계층적 비전 트랜스포머",
            authors: ["Ze Liu","Yutong Lin","Yue Cao","et al."],
            year: 2021,
            venue: "ICCV 2021",
            venueType: "iccv",
            award: "best-paper",
            arxivUrl: "https://arxiv.org/abs/2103.14030",
            tags: [],
            status: "complete",
            citations: "18,000+",
          },
        ],
      },
      {
        year: 2022,
        papers: [
          {
            id: "convnext",
            title: "A ConvNet for the 2020s",
            titleKo: "2020년대를 위한 합성곱 네트워크",
            authors: ["Zhuang Liu","Hanzi Mao","Chao-Yuan Wu","et al."],
            year: 2022,
            venue: "CVPR 2022",
            venueType: "cvpr",
            arxivUrl: "https://arxiv.org/abs/2201.03545",
            tags: [],
            status: "complete",
            citations: "5,000+",
          },
        ],
      },
      {
        year: 2023,
        papers: [
          {
            id: "sam",
            title: "Segment Anything",
            titleKo: "무엇이든 분할하기",
            authors: ["Alexander Kirillov","Eric Mintun","Nikhila Ravi","et al."],
            year: 2023,
            venue: "ICCV 2023",
            venueType: "iccv",
            arxivUrl: "https://arxiv.org/abs/2304.02643",
            tags: [],
            status: "complete",
            citations: "5,000+",
          },
          {
            id: "dinov2",
            title: "DINOv2: Learning Robust Visual Features without Supervision",
            titleKo: "DINOv2: 감독 없이 강건한 시각적 특징 학습",
            authors: ["Maxime Oquab","Timothée Darcet","Théo Moutakanni","et al."],
            year: 2023,
            venue: "TMLR 2024",
            venueType: "other",
            arxivUrl: "https://arxiv.org/abs/2304.07193",
            tags: [],
            status: "complete",
            citations: "3,000+",
          },
        ],
      },
    ],
  },
  {
    id: "generative",
    titleKo: "생성 모델",
    titleEn: "Generative Models",
    descriptionKo: "GAN, VAE, Diffusion, Flow 등 데이터 생성에 관한 연구",
    descriptionEn: "Research on data generation models",
    color: "cyan",
    years: [
      {
        year: 2017,
        papers: [
          {
            id: "wgan",
            title: "Wasserstein GAN",
            titleKo: "바서슈타인 GAN",
            authors: ["Martin Arjovsky","Soumith Chintala","Léon Bottou"],
            year: 2017,
            venue: "ICML 2017",
            venueType: "icml",
            arxivUrl: "https://arxiv.org/abs/1701.07875",
            tags: ["theory"],
            status: "complete",
            citations: "12,000+",
          },
          {
            id: "pix2pix",
            title: "Image-to-Image Translation with Conditional Adversarial Networks",
            titleKo: "조건부 적대적 네트워크를 이용한 이미지-이미지 변환",
            authors: ["Phillip Isola","Jun-Yan Zhu","Tinghui Zhou","Alexei A. Efros"],
            year: 2017,
            venue: "CVPR 2017",
            venueType: "cvpr",
            arxivUrl: "https://arxiv.org/abs/1611.07004",
            tags: [],
            status: "complete",
            citations: "20,000+",
          },
          {
            id: "cyclegan",
            title: "Unpaired Image-to-Image Translation using Cycle-Consistent Adversarial Networks",
            titleKo: "순환 일관성 적대적 네트워크를 이용한 비짝 이미지-이미지 변환",
            authors: ["Jun-Yan Zhu","Taesung Park","Phillip Isola","Alexei A. Efros"],
            year: 2017,
            venue: "ICCV 2017",
            venueType: "iccv",
            arxivUrl: "https://arxiv.org/abs/1703.10593",
            tags: [],
            status: "complete",
            citations: "18,000+",
          },
        ],
      },
      {
        year: 2019,
        papers: [
          {
            id: "stylegan",
            title: "A Style-Based Generator Architecture for Generative Adversarial Networks",
            titleKo: "생성적 적대 신경망을 위한 스타일 기반 생성기 아키텍처",
            authors: ["Tero Karras","Samuli Laine","Timo Aila"],
            year: 2019,
            venue: "CVPR 2019",
            venueType: "cvpr",
            arxivUrl: "https://arxiv.org/abs/1812.04948",
            tags: [],
            status: "complete",
            citations: "12,000+",
          },
          {
            id: "vqvae2",
            title: "Generating Diverse High-Fidelity Images with VQ-VAE-2",
            titleKo: "VQ-VAE-2를 이용한 다양하고 고품질의 이미지 생성",
            authors: ["Ali Razavi","Aaron van den Oord","Oriol Vinyals"],
            year: 2019,
            venue: "NeurIPS 2019",
            venueType: "neurips",
            arxivUrl: "https://arxiv.org/abs/1906.00446",
            tags: [],
            status: "complete",
            citations: "2,000+",
          },
        ],
      },
      {
        year: 2020,
        papers: [
          {
            id: "ddim",
            title: "Denoising Diffusion Implicit Models",
            titleKo: "노이즈 제거 확산 암묵적 모델",
            authors: ["Jiaming Song","Chenlin Meng","Stefano Ermon"],
            year: 2020,
            venue: "ICLR 2021",
            venueType: "iclr",
            arxivUrl: "https://arxiv.org/abs/2010.02502",
            tags: [],
            status: "complete",
            citations: "8,000+",
          },
        ],
      },
      {
        year: 2022,
        papers: [
          {
            id: "ldm",
            title: "High-Resolution Image Synthesis with Latent Diffusion Models",
            titleKo: "잠재 확산 모델을 이용한 고해상도 이미지 합성",
            authors: ["Robin Rombach","Andreas Blattmann","Dominik Lorenz","et al."],
            year: 2022,
            venue: "CVPR 2022",
            venueType: "cvpr",
            award: "oral",
            arxivUrl: "https://arxiv.org/abs/2112.10752",
            tags: [],
            status: "complete",
            citations: "12,000+",
          },
          {
            id: "dalle2",
            title: "Hierarchical Text-Conditional Image Generation with CLIP Latents",
            titleKo: "CLIP 잠재 변수를 이용한 계층적 텍스트 조건 이미지 생성",
            authors: ["Aditya Ramesh","Prafulla Dhariwal","Alex Nichol","et al."],
            year: 2022,
            venue: "arXiv",
            venueType: "arxiv",
            arxivUrl: "https://arxiv.org/abs/2204.06125",
            tags: [],
            status: "complete",
            citations: "5,000+",
          },
          {
            id: "classifier-free-guidance",
            title: "Classifier-Free Diffusion Guidance",
            titleKo: "분류기 없는 확산 가이던스",
            authors: ["Jonathan Ho","Tim Salimans"],
            year: 2022,
            venue: "NeurIPS 2022 Workshop",
            venueType: "neurips",
            arxivUrl: "https://arxiv.org/abs/2207.12598",
            tags: [],
            status: "complete",
            citations: "5,000+",
          },
        ],
      },
      {
        year: 2023,
        papers: [
          {
            id: "flow-matching",
            title: "Flow Matching for Generative Modeling",
            titleKo: "생성 모델링을 위한 플로우 매칭",
            authors: ["Yaron Lipman","Ricky T. Q. Chen","Heli Ben-Hamu","Maximilian Nickel"],
            year: 2023,
            venue: "ICLR 2023",
            venueType: "iclr",
            arxivUrl: "https://arxiv.org/abs/2210.02747",
            tags: ["theory"],
            status: "complete",
            citations: "1,000+",
          },
          {
            id: "consistency-models",
            title: "Consistency Models",
            titleKo: "일관성 모델",
            authors: ["Yang Song","Prafulla Dhariwal","Mark Chen","Ilya Sutskever"],
            year: 2023,
            venue: "ICML 2023",
            venueType: "icml",
            arxivUrl: "https://arxiv.org/abs/2303.01469",
            tags: [],
            status: "complete",
            citations: "1,500+",
          },
        ],
      },
    ],
  },
  {
    id: "rl",
    titleKo: "강화학습",
    titleEn: "Reinforcement Learning",
    descriptionKo: "MDP, 정책 경사, Actor-Critic, MARL, 게임 AI 등",
    descriptionEn: "Research on learning from interaction and rewards",
    color: "rose",
    years: [
      {
        year: 2013,
        papers: [
          {
            id: "dqn",
            title: "Playing Atari with Deep Reinforcement Learning",
            titleKo: "심층 강화학습으로 Atari 게임하기",
            authors: ["Volodymyr Mnih","Kavukcuoglu","Silver","et al."],
            year: 2013,
            venue: "NeurIPS 2013 Workshop",
            venueType: "neurips",
            arxivUrl: "https://arxiv.org/abs/1312.5602",
            tags: [],
            status: "complete",
            citations: "15,000+",
          },
        ],
      },
      {
        year: 2016,
        papers: [
          {
            id: "alphago",
            title: "Mastering the game of Go with deep neural networks and tree search",
            titleKo: "심층 신경망과 트리 탐색으로 바둑 마스터하기",
            authors: ["David Silver","Aja Huang","Chris J. Maddison","et al."],
            year: 2016,
            venue: "Nature",
            venueType: "nature",
            arxivUrl: "https://doi.org/10.1038/nature16961",
            tags: [],
            status: "complete",
            citations: "18,000+",
          },
          {
            id: "a3c",
            title: "Asynchronous Methods for Deep Reinforcement Learning",
            titleKo: "딥 강화학습을 위한 비동기 방법",
            authors: ["Volodymyr Mnih","Adrià Puigdomènech Badia","et al."],
            year: 2016,
            venue: "ICML 2016",
            venueType: "icml",
            arxivUrl: "https://arxiv.org/abs/1602.01783",
            tags: [],
            status: "complete",
            citations: "12,000+",
          },
        ],
      },
      {
        year: 2017,
        papers: [
          {
            id: "ppo",
            title: "Proximal Policy Optimization Algorithms",
            titleKo: "근접 정책 최적화 알고리즘",
            authors: ["John Schulman","Filip Wolski","Prafulla Dhariwal","et al."],
            year: 2017,
            venue: "arXiv",
            venueType: "arxiv",
            arxivUrl: "https://arxiv.org/abs/1707.06347",
            tags: [],
            status: "complete",
            citations: "15,000+",
          },
          {
            id: "alphazero",
            title: "Mastering Chess and Shogi by Self-Play with a General Reinforcement Learning Algorithm",
            titleKo: "범용 강화학습 알고리즘의 자기대국으로 체스와 쇼기 마스터하기",
            authors: ["David Silver","Thomas Hubert","Julian Schrittwieser","et al."],
            year: 2017,
            venue: "arXiv",
            venueType: "arxiv",
            arxivUrl: "https://arxiv.org/abs/1712.01815",
            tags: [],
            status: "complete",
            citations: "5,000+",
          },
        ],
      },
      {
        year: 2018,
        papers: [
          {
            id: "sac",
            title: "Soft Actor-Critic: Off-Policy Maximum Entropy Deep Reinforcement Learning with a Stochastic Actor",
            titleKo: "소프트 액터-크리틱: 확률적 액터를 이용한 오프폴리시 최대 엔트로피 딥 강화학습",
            authors: ["Tuomas Haarnoja","Aurick Zhou","Pieter Abbeel","Sergey Levine"],
            year: 2018,
            venue: "ICML 2018",
            venueType: "icml",
            arxivUrl: "https://arxiv.org/abs/1801.01290",
            tags: [],
            status: "complete",
            citations: "8,000+",
          },
        ],
      },
      {
        year: 2019,
        papers: [
          {
            id: "muzero",
            title: "Mastering Atari, Go, Chess and Shogi by Planning with a Learned Model",
            titleKo: "학습된 모델로 계획하여 Atari, 바둑, 체스, 장기 마스터하기",
            authors: ["Julian Schrittwieser","Ioannis Antonoglou","Thomas Hubert","et al."],
            year: 2019,
            venue: "Nature 2020",
            venueType: "nature",
            arxivUrl: "https://arxiv.org/abs/1911.08265",
            tags: [],
            status: "complete",
            citations: "3,000+",
          },
          {
            id: "alphastar",
            title: "Grandmaster level in StarCraft II using multi-agent reinforcement learning",
            titleKo: "다중 에이전트 강화학습을 이용한 스타크래프트 II 그랜드마스터 달성",
            authors: ["Oriol Vinyals","Igor Babuschkin","et al."],
            year: 2019,
            venue: "Nature",
            venueType: "nature",
            conferenceUrl: "https://doi.org/10.1038/s41586-019-1724-z",
            tags: [],
            status: "complete",
            citations: "3,000+",
          },
        ],
      },
      {
        year: 2021,
        papers: [
          {
            id: "decision-transformer",
            title: "Decision Transformer: Reinforcement Learning via Sequence Modeling",
            titleKo: "결정 트랜스포머: 시퀀스 모델링을 통한 강화학습",
            authors: ["Lili Chen","Kevin Lu","Aravind Rajeswaran","et al."],
            year: 2021,
            venue: "NeurIPS 2021",
            venueType: "neurips",
            arxivUrl: "https://arxiv.org/abs/2106.01345",
            tags: [],
            status: "complete",
            citations: "2,500+",
          },
        ],
      },
      {
        year: 2023,
        papers: [
          {
            id: "dreamerv3",
            title: "Mastering Diverse Domains through World Models",
            titleKo: "월드 모델을 통한 다양한 도메인 마스터하기",
            authors: ["Danijar Hafner","Jurgis Pasukonis","Jimmy Ba","Timothy Lillicrap"],
            year: 2023,
            venue: "arXiv",
            venueType: "arxiv",
            arxivUrl: "https://arxiv.org/abs/2301.04104",
            tags: [],
            status: "complete",
            citations: "1,000+",
          },
        ],
      },
    ],
  },
  {
    id: "llm",
    titleKo: "대규모 언어모델",
    titleEn: "Large Language Models",
    descriptionKo: "스케일링, RLHF, 프롬프팅, RAG, 에이전트, 추론 등",
    descriptionEn: "Research on scaling and capabilities of language models",
    color: "amber",
    years: [
      {
        year: 2021,
        papers: [
          {
            id: "codex",
            title: "Evaluating Large Language Models Trained on Code",
            titleKo: "코드로 학습된 대규모 언어 모델 평가",
            authors: ["Mark Chen","Jerry Tworek","Heewoo Jun","et al."],
            year: 2021,
            venue: "arXiv",
            venueType: "arxiv",
            arxivUrl: "https://arxiv.org/abs/2107.03374",
            tags: [],
            status: "complete",
            citations: "5,000+",
          },
        ],
      },
      {
        year: 2022,
        papers: [
          {
            id: "chinchilla",
            title: "Training Compute-Optimal Large Language Models",
            titleKo: "계산 최적 대규모 언어 모델 학습",
            authors: ["Jordan Hoffmann","Sebastian Borgeaud","Arthur Mensch","et al."],
            year: 2022,
            venue: "NeurIPS 2022",
            venueType: "neurips",
            arxivUrl: "https://arxiv.org/abs/2203.15556",
            tags: [],
            status: "complete",
            citations: "3,000+",
          },
          {
            id: "cot",
            title: "Chain-of-Thought Prompting Elicits Reasoning in Large Language Models",
            titleKo: "연쇄 사고 프롬프팅은 대규모 언어 모델에서 추론을 이끌어낸다",
            authors: ["Jason Wei","Xuezhi Wang","Dale Schuurmans","et al."],
            year: 2022,
            venue: "NeurIPS 2022",
            venueType: "neurips",
            award: "outstanding-paper",
            arxivUrl: "https://arxiv.org/abs/2201.11903",
            tags: [],
            status: "complete",
            citations: "5,000+",
          },
          {
            id: "palm",
            title: "PaLM: Scaling Language Modeling with Pathways",
            titleKo: "PaLM: Pathways를 활용한 언어 모델링 스케일링",
            authors: ["Aakanksha Chowdhery","Sharan Narang","Jacob Devlin","et al."],
            year: 2022,
            venue: "arXiv",
            venueType: "arxiv",
            arxivUrl: "https://arxiv.org/abs/2204.02311",
            tags: [],
            status: "complete",
            citations: "7,000+",
          },
        ],
      },
      {
        year: 2023,
        papers: [
          {
            id: "llama",
            title: "LLaMA: Open and Efficient Foundation Language Models",
            titleKo: "LLaMA: 개방적이고 효율적인 기초 언어 모델",
            authors: ["Hugo Touvron","Thibaut Lavril","Gautier Izacard","et al."],
            year: 2023,
            venue: "arXiv",
            venueType: "arxiv",
            arxivUrl: "https://arxiv.org/abs/2302.13971",
            tags: [],
            status: "complete",
            citations: "8,000+",
          },
          {
            id: "gpt4",
            title: "GPT-4 Technical Report",
            titleKo: "GPT-4 기술 보고서",
            authors: ["OpenAI"],
            year: 2023,
            venue: "arXiv",
            venueType: "arxiv",
            arxivUrl: "https://arxiv.org/abs/2303.08774",
            tags: [],
            status: "complete",
            citations: "5,000+",
          },
          {
            id: "rag",
            title: "Retrieval-Augmented Generation for Knowledge-Intensive NLP Tasks",
            titleKo: "지식 집약적 NLP 태스크를 위한 검색 증강 생성",
            authors: ["Patrick Lewis","Ethan Perez","Aleksandra Piktus","et al."],
            year: 2020,
            venue: "NeurIPS 2020",
            venueType: "neurips",
            arxivUrl: "https://arxiv.org/abs/2005.11401",
            tags: [],
            status: "complete",
            citations: "4,000+",
          },
          {
            id: "llama2",
            title: "Llama 2: Open Foundation and Fine-Tuned Chat Models",
            titleKo: "Llama 2: 개방형 파운데이션 및 미세조정 채팅 모델",
            authors: ["Hugo Touvron","Louis Martin","Kevin Stone","et al."],
            year: 2023,
            venue: "arXiv",
            venueType: "arxiv",
            arxivUrl: "https://arxiv.org/abs/2307.09288",
            tags: [],
            status: "complete",
            citations: "10,000+",
          },
        ],
      },
      {
        year: 2024,
        papers: [
          {
            id: "mixtral",
            title: "Mixtral of Experts",
            titleKo: "Mixtral: 전문가 혼합 모델",
            authors: ["Albert Q. Jiang","Alexandre Sablayrolles","Antoine Roux","et al."],
            year: 2024,
            venue: "arXiv",
            venueType: "arxiv",
            arxivUrl: "https://arxiv.org/abs/2401.04088",
            tags: [],
            status: "complete",
            citations: "2,000+",
          },
          {
            id: "gemma",
            title: "Gemma: Open Models Based on Gemini Research and Technology",
            titleKo: "Gemma: Gemini 연구와 기술 기반의 오픈 모델",
            authors: ["Gemma Team","Thomas Mesnard","Cassidy Hardin","et al."],
            year: 2024,
            venue: "arXiv",
            venueType: "arxiv",
            arxivUrl: "https://arxiv.org/abs/2403.08295",
            tags: [],
            status: "complete",
            citations: "1,000+",
          },
        ],
      },
    ],
  },
  {
    id: "multimodal",
    titleKo: "멀티모달",
    titleEn: "Multimodal AI",
    descriptionKo: "비전-언어, 오디오-텍스트, 통합 모델 연구",
    descriptionEn: "Research on multi-modal understanding and generation",
    color: "teal",
    years: [
      {
        year: 2019,
        papers: [
          {
            id: "vilbert",
            title: "ViLBERT: Pretraining Task-Agnostic Visiolinguistic Representations for Vision-and-Language Tasks",
            titleKo: "ViLBERT: 비전-언어 과제를 위한 과제 비의존적 시각언어 표현 사전학습",
            authors: ["Jiasen Lu","Dhruv Batra","Devi Parikh","Stefan Lee"],
            year: 2019,
            venue: "NeurIPS 2019",
            venueType: "neurips",
            arxivUrl: "https://arxiv.org/abs/1908.02265",
            tags: [],
            status: "complete",
            citations: "3,000+",
          },
        ],
      },
      {
        year: 2021,
        papers: [
          {
            id: "clip",
            title: "Learning Transferable Visual Models From Natural Language Supervision",
            titleKo: "자연어 감독으로 전이 가능한 시각 모델 학습",
            authors: ["Alec Radford","Jong Wook Kim","Chris Hallacy","et al."],
            year: 2021,
            venue: "ICML 2021",
            venueType: "icml",
            arxivUrl: "https://arxiv.org/abs/2103.00020",
            tags: [],
            status: "complete",
            citations: "20,000+",
          },
          {
            id: "dall-e",
            title: "Zero-Shot Text-to-Image Generation",
            titleKo: "제로샷 텍스트-이미지 생성",
            authors: ["Aditya Ramesh","Mikhail Pavlov","Gabriel Goh","et al."],
            year: 2021,
            venue: "ICML 2021",
            venueType: "icml",
            arxivUrl: "https://arxiv.org/abs/2102.12092",
            tags: [],
            status: "complete",
            citations: "5,000+",
          },
          {
            id: "align",
            title: "Scaling Up Visual and Vision-Language Representation Learning With Noisy Text Supervision",
            titleKo: "노이즈가 포함된 텍스트 감독을 활용한 시각 및 비전-언어 표현 학습의 스케일링",
            authors: ["Chao Jia","Yinfei Yang","Ye Xia","et al."],
            year: 2021,
            venue: "ICML 2021",
            venueType: "icml",
            arxivUrl: "https://arxiv.org/abs/2102.05918",
            tags: [],
            status: "complete",
            citations: "3,000+",
          },
        ],
      },
      {
        year: 2022,
        papers: [
          {
            id: "flamingo",
            title: "Flamingo: a Visual Language Model for Few-Shot Learning",
            titleKo: "Flamingo: 퓨샷 학습을 위한 시각 언어 모델",
            authors: ["Jean-Baptiste Alayrac","Jeff Donahue","Pauline Luc","et al."],
            year: 2022,
            venue: "NeurIPS 2022",
            venueType: "neurips",
            arxivUrl: "https://arxiv.org/abs/2204.14198",
            tags: [],
            status: "complete",
            citations: "3,000+",
          },
        ],
      },
      {
        year: 2023,
        papers: [
          {
            id: "llava",
            title: "Visual Instruction Tuning",
            titleKo: "시각적 지시 튜닝",
            authors: ["Haotian Liu","Chunyuan Li","Qingyang Wu","Yong Jae Lee"],
            year: 2023,
            venue: "NeurIPS 2023",
            venueType: "neurips",
            award: "oral",
            arxivUrl: "https://arxiv.org/abs/2304.08485",
            tags: [],
            status: "complete",
            citations: "3,000+",
          },
          {
            id: "blip2",
            title: "BLIP-2: Bootstrapping Language-Image Pre-training with Frozen Image Encoders and Large Language Models",
            titleKo: "BLIP-2: 동결된 이미지 인코더와 대규모 언어 모델을 활용한 언어-이미지 사전학습 부트스트래핑",
            authors: ["Junnan Li","Dongxu Li","Silvio Savarese","Steven Hoi"],
            year: 2023,
            venue: "ICML 2023",
            venueType: "icml",
            arxivUrl: "https://arxiv.org/abs/2301.12597",
            tags: [],
            status: "complete",
            citations: "5,000+",
          },
          {
            id: "cogvlm",
            title: "CogVLM: Visual Expert for Pretrained Language Models",
            titleKo: "CogVLM: 사전학습된 언어 모델을 위한 시각 전문가",
            authors: ["Weihan Wang","Qingsong Lv","Wenmeng Yu","et al."],
            year: 2023,
            venue: "arXiv",
            venueType: "arxiv",
            arxivUrl: "https://arxiv.org/abs/2311.03079",
            tags: [],
            status: "complete",
            citations: "1,000+",
          },
        ],
      },
      {
        year: 2024,
        papers: [
          {
            id: "gemini",
            title: "Gemini: A Family of Highly Capable Multimodal Models",
            titleKo: "Gemini: 고성능 멀티모달 모델 패밀리",
            authors: ["Gemini Team","Google DeepMind"],
            year: 2024,
            venue: "arXiv",
            venueType: "arxiv",
            arxivUrl: "https://arxiv.org/abs/2312.11805",
            tags: [],
            status: "complete",
            citations: "3,000+",
          },
          {
            id: "internvl",
            title: "InternVL: Scaling up Vision Foundation Models and Aligning for Generic Visual-Linguistic Tasks",
            titleKo: "InternVL: 범용 시각-언어 과제를 위한 비전 파운데이션 모델 스케일링 및 정렬",
            authors: ["Zhe Chen","Jiannan Wu","Wenhai Wang","et al."],
            year: 2024,
            venue: "CVPR 2024",
            venueType: "cvpr",
            arxivUrl: "https://arxiv.org/abs/2312.14238",
            tags: [],
            status: "complete",
            citations: "1,000+",
          },
        ],
      },
    ],
  },
  {
    id: "graph",
    titleKo: "그래프 ML",
    titleEn: "Graph Machine Learning",
    descriptionKo: "GNN, Knowledge Graph, 분자 그래프 등 그래프 구조 학습",
    descriptionEn: "Research on learning from graph-structured data",
    color: "indigo",
    years: [
      {
        year: 2016,
        papers: [
          {
            id: "gcn",
            title: "Semi-Supervised Classification with Graph Convolutional Networks",
            titleKo: "그래프 합성곱 네트워크를 이용한 준지도 분류",
            authors: ["Thomas N. Kipf","Max Welling"],
            year: 2016,
            venue: "ICLR 2017",
            venueType: "iclr",
            arxivUrl: "https://arxiv.org/abs/1609.02907",
            tags: [],
            status: "complete",
            citations: "25,000+",
          },
        ],
      },
      {
        year: 2017,
        papers: [
          {
            id: "gat",
            title: "Graph Attention Networks",
            titleKo: "그래프 어텐션 네트워크",
            authors: ["Petar Veličković","Guillem Cucurull","Arantxa Casanova","et al."],
            year: 2017,
            venue: "ICLR 2018",
            venueType: "iclr",
            arxivUrl: "https://arxiv.org/abs/1710.10903",
            tags: [],
            status: "complete",
            citations: "15,000+",
          },
          {
            id: "graphsage",
            title: "Inductive Representation Learning on Large Graphs",
            titleKo: "대규모 그래프에서의 귀납적 표현 학습",
            authors: ["William L. Hamilton","Rex Ying","Jure Leskovec"],
            year: 2017,
            venue: "NeurIPS 2017",
            venueType: "neurips",
            arxivUrl: "https://arxiv.org/abs/1706.02216",
            tags: [],
            status: "complete",
            citations: "10,000+",
          },
          {
            id: "mpnn",
            title: "Neural Message Passing for Quantum Chemistry",
            titleKo: "양자 화학을 위한 신경 메시지 전달",
            authors: ["Justin Gilmer","Samuel S. Schoenholz","Patrick F. Riley","et al."],
            year: 2017,
            venue: "ICML 2017",
            venueType: "icml",
            arxivUrl: "https://arxiv.org/abs/1704.01212",
            tags: [],
            status: "complete",
            citations: "5,000+",
          },
        ],
      },
      {
        year: 2018,
        papers: [
          {
            id: "schnet",
            title: "SchNet: A continuous-filter convolutional neural network for modeling quantum interactions",
            titleKo: "SchNet: 양자 상호작용 모델링을 위한 연속 필터 합성곱 신경망",
            authors: ["Kristof T. Schütt","Pieter-Jan Kindermans","Huziel E. Sauceda","et al."],
            year: 2018,
            venue: "NeurIPS 2017",
            venueType: "neurips",
            arxivUrl: "https://arxiv.org/abs/1706.08566",
            tags: [],
            status: "complete",
            citations: "3,000+",
          },
        ],
      },
      {
        year: 2019,
        papers: [
          {
            id: "gin",
            title: "How Powerful are Graph Neural Networks?",
            titleKo: "그래프 신경망은 얼마나 강력한가?",
            authors: ["Keyulu Xu","Weihua Hu","Jure Leskovec","Stefanie Jegelka"],
            year: 2019,
            venue: "ICLR 2019",
            venueType: "iclr",
            arxivUrl: "https://arxiv.org/abs/1810.00826",
            tags: [],
            status: "complete",
            citations: "5,000+",
          },
        ],
      },
      {
        year: 2020,
        papers: [
          {
            id: "ogb",
            title: "Open Graph Benchmark: Datasets for Machine Learning on Graphs",
            titleKo: "오픈 그래프 벤치마크: 그래프 머신러닝을 위한 데이터셋",
            authors: ["Weihua Hu","Matthias Fey","Marinka Zitnik","et al."],
            year: 2020,
            venue: "NeurIPS 2020",
            venueType: "neurips",
            arxivUrl: "https://arxiv.org/abs/2005.00687",
            tags: ["benchmark"],
            status: "complete",
            citations: "2,500+",
          },
        ],
      },
      {
        year: 2021,
        papers: [
          {
            id: "egnn",
            title: "E(n) Equivariant Graph Neural Networks",
            titleKo: "E(n) 등변 그래프 신경망",
            authors: ["Victor Garcia Satorras","Emiel Hoogeboom","Max Welling"],
            year: 2021,
            venue: "ICML 2021",
            venueType: "icml",
            arxivUrl: "https://arxiv.org/abs/2102.09844",
            tags: [],
            status: "complete",
            citations: "1,500+",
          },
        ],
      },
      {
        year: 2022,
        papers: [
          {
            id: "graphgps",
            title: "Recipe for a General, Powerful, Scalable Graph Transformer",
            titleKo: "범용적이고 강력하며 확장 가능한 그래프 트랜스포머의 레시피",
            authors: ["Ladislav Rampášek","Mikhail Galkin","Vijay Prakash Dwivedi","et al."],
            year: 2022,
            venue: "NeurIPS 2022",
            venueType: "neurips",
            arxivUrl: "https://arxiv.org/abs/2205.12454",
            tags: [],
            status: "complete",
            citations: "500+",
          },
          {
            id: "graphmae",
            title: "GraphMAE: Self-Supervised Masked Graph Autoencoders",
            titleKo: "GraphMAE: 자기지도 마스크 그래프 오토인코더",
            authors: ["Zhenyu Hou","Xiao Liu","Yukuo Cen","et al."],
            year: 2022,
            venue: "KDD 2022",
            venueType: "other",
            arxivUrl: "https://arxiv.org/abs/2205.10803",
            tags: [],
            status: "complete",
            citations: "600+",
          },
        ],
      },
    ],
  },
  {
    id: "robotics",
    titleKo: "로보틱스",
    titleEn: "Robotics & Embodied AI",
    descriptionKo: "조작, 내비게이션, Sim2Real, 체화 에이전트 연구",
    descriptionEn: "Research on robotic manipulation, navigation, and embodied agents",
    color: "red",
    years: [
      {
        year: 2021,
        papers: [
          {
            id: "bcz",
            title: "BC-Z: Zero-Shot Task Generalization with Robotic Imitation Learning",
            titleKo: "BC-Z: 로봇 모방학습을 이용한 제로샷 태스크 일반화",
            authors: ["Eric Jang","Alex Irpan","Mohi Khansari","et al."],
            year: 2021,
            venue: "CoRL 2021",
            venueType: "other",
            arxivUrl: "https://arxiv.org/abs/2202.02005",
            tags: [],
            status: "complete",
            citations: "300+",
          },
          {
            id: "cliport",
            title: "CLIPort: What and Where Pathways for Robotic Manipulation",
            titleKo: "CLIPort: 로봇 조작을 위한 What and Where 경로",
            authors: ["Mohit Shridhar","Lucas Manuelli","Dieter Fox"],
            year: 2021,
            venue: "CoRL 2021",
            venueType: "other",
            arxivUrl: "https://arxiv.org/abs/2109.12098",
            tags: [],
            status: "complete",
            citations: "500+",
          },
        ],
      },
      {
        year: 2022,
        papers: [
          {
            id: "saycan",
            title: "Do As I Can, Not As I Say: Grounding Language in Robotic Affordances",
            titleKo: "내가 하는 대로 해, 말하는 대로가 아니라: 로봇 어포던스에서의 언어 접지",
            authors: ["Michael Ahn","Anthony Brohan","Noah Brown","et al."],
            year: 2022,
            venue: "arXiv",
            venueType: "arxiv",
            arxivUrl: "https://arxiv.org/abs/2204.01691",
            tags: [],
            status: "complete",
            citations: "1,500+",
          },
          {
            id: "rt1",
            title: "RT-1: Robotics Transformer for Real-World Control at Scale",
            titleKo: "RT-1: 대규모 실세계 제어를 위한 로보틱스 트랜스포머",
            authors: ["Anthony Brohan","Noah Brown","Justice Carbajal","et al."],
            year: 2022,
            venue: "RSS 2023",
            venueType: "other",
            arxivUrl: "https://arxiv.org/abs/2212.06817",
            tags: [],
            status: "complete",
            citations: "800+",
          },
          {
            id: "inner-monologue",
            title: "Inner Monologue: Embodied Reasoning through Planning with Language Models",
            titleKo: "내면 독백: 언어 모델을 이용한 체화된 추론과 계획",
            authors: ["Wenlong Huang","Fei Xia","Ted Xiao","et al."],
            year: 2022,
            venue: "CoRL 2022",
            venueType: "other",
            arxivUrl: "https://arxiv.org/abs/2207.05608",
            tags: [],
            status: "complete",
            citations: "600+",
          },
          {
            id: "gato",
            title: "A Generalist Agent",
            titleKo: "범용 에이전트",
            authors: ["Scott Reed","Konrad Żołna","Emilio Parisotto","et al."],
            year: 2022,
            venue: "TMLR 2022",
            venueType: "other",
            arxivUrl: "https://arxiv.org/abs/2205.06175",
            tags: [],
            status: "complete",
            citations: "1,500+",
          },
        ],
      },
      {
        year: 2023,
        papers: [
          {
            id: "rt2",
            title: "RT-2: Vision-Language-Action Models Transfer Web Knowledge to Robotic Control",
            titleKo: "RT-2: 비전-언어-행동 모델이 웹 지식을 로봇 제어로 전이",
            authors: ["Anthony Brohan","Noah Brown","Justice Carbajal","et al."],
            year: 2023,
            venue: "arXiv",
            venueType: "arxiv",
            arxivUrl: "https://arxiv.org/abs/2307.15818",
            tags: [],
            status: "complete",
            citations: "500+",
          },
          {
            id: "voxposer",
            title: "VoxPoser: Composable 3D Value Maps for Robotic Manipulation with Language Models",
            titleKo: "VoxPoser: 언어 모델을 이용한 로봇 조작용 합성형 3D 가치 맵",
            authors: ["Wenlong Huang","Chen Wang","Ruohan Zhang","et al."],
            year: 2023,
            venue: "CoRL 2023",
            venueType: "other",
            arxivUrl: "https://arxiv.org/abs/2307.05973",
            tags: [],
            status: "complete",
            citations: "300+",
          },
          {
            id: "aloha",
            title: "Learning Fine-Grained Bimanual Manipulation with Low-Cost Hardware",
            titleKo: "저비용 하드웨어를 이용한 정밀 양손 조작 학습",
            authors: ["Tony Z. Zhao","Vikash Kumar","Sergey Levine","Chelsea Finn"],
            year: 2023,
            venue: "RSS 2023",
            venueType: "other",
            arxivUrl: "https://arxiv.org/abs/2304.13705",
            tags: [],
            status: "complete",
            citations: "400+",
          },
        ],
      },
      {
        year: 2024,
        papers: [
          {
            id: "mobile-aloha",
            title: "Mobile ALOHA: Learning Bimanual Mobile Manipulation with Low-Cost Whole-Body Teleoperation",
            titleKo: "Mobile ALOHA: 저비용 전신 원격조작을 이용한 양손 이동 조작 학습",
            authors: ["Zipeng Fu","Tony Z. Zhao","Chelsea Finn"],
            year: 2024,
            venue: "arXiv",
            venueType: "arxiv",
            arxivUrl: "https://arxiv.org/abs/2401.02117",
            tags: [],
            status: "complete",
            citations: "200+",
          },
        ],
      },
    ],
  },
  {
    id: "safety",
    titleKo: "AI 안전성·정렬",
    titleEn: "AI Safety & Alignment",
    descriptionKo: "정렬, 해석 가능성, 레드팀, 거버넌스 연구",
    descriptionEn: "Research on making AI systems safe and aligned",
    color: "fuchsia",
    years: [
      {
        year: 2014,
        papers: [
          {
            id: "adversarial-examples",
            title: "Explaining and Harnessing Adversarial Examples",
            titleKo: "적대적 예제의 설명과 활용",
            authors: ["Ian J. Goodfellow","Jonathon Shlens","Christian Szegedy"],
            year: 2014,
            venue: "ICLR 2015",
            venueType: "iclr",
            arxivUrl: "https://arxiv.org/abs/1412.6572",
            tags: [],
            status: "complete",
            citations: "15,000+",
          },
        ],
      },
      {
        year: 2019,
        papers: [
          {
            id: "certified-defenses",
            title: "Certified Adversarial Robustness via Randomized Smoothing",
            titleKo: "랜덤 평활화를 통한 인증된 적대적 강건성",
            authors: ["Jeremy Cohen","Elan Rosenfeld","J. Zico Kolter"],
            year: 2019,
            venue: "ICML 2019",
            venueType: "icml",
            arxivUrl: "https://arxiv.org/abs/1902.02918",
            tags: [],
            status: "complete",
            citations: "2,000+",
          },
        ],
      },
      {
        year: 2021,
        papers: [
          {
            id: "truthfulqa",
            title: "TruthfulQA: Measuring How Models Mimic Human Falsehoods",
            titleKo: "TruthfulQA: 모델이 인간의 거짓을 모방하는 정도 측정",
            authors: ["Stephanie Lin","Jacob Hilton","Owain Evans"],
            year: 2021,
            venue: "ACL 2022",
            venueType: "acl",
            arxivUrl: "https://arxiv.org/abs/2109.07958",
            tags: [],
            status: "complete",
            citations: "1,500+",
          },
        ],
      },
      {
        year: 2022,
        papers: [
          {
            id: "constitutional-ai",
            title: "Constitutional AI: Harmlessness from AI Feedback",
            titleKo: "헌법적 AI: AI 피드백을 통한 무해성",
            authors: ["Yuntao Bai","Saurav Kadavath","Sandipan Kundu","et al."],
            year: 2022,
            venue: "arXiv",
            venueType: "arxiv",
            arxivUrl: "https://arxiv.org/abs/2212.08073",
            tags: [],
            status: "complete",
            citations: "1,500+",
          },
          {
            id: "rlhf",
            title: "Training a Helpful and Harmless Assistant with RLHF",
            titleKo: "RLHF로 도움이 되고 무해한 어시스턴트 학습",
            authors: ["Yuntao Bai","Andy Jones","Kamal Ndousse","et al."],
            year: 2022,
            venue: "arXiv",
            venueType: "arxiv",
            arxivUrl: "https://arxiv.org/abs/2204.05862",
            tags: [],
            status: "complete",
            citations: "2,000+",
          },
          {
            id: "red-teaming",
            title: "Red Teaming Language Models to Reduce Harms",
            titleKo: "피해 감소를 위한 언어 모델 레드팀 테스팅",
            authors: ["Deep Ganguli","Liane Lovitt","Jackson Kernion","et al."],
            year: 2022,
            venue: "arXiv",
            venueType: "arxiv",
            arxivUrl: "https://arxiv.org/abs/2209.07858",
            tags: [],
            status: "complete",
            citations: "800+",
          },
        ],
      },
      {
        year: 2023,
        papers: [
          {
            id: "interpretability-circuits",
            title: "Towards Monosemanticity: Decomposing Language Models With Dictionary Learning",
            titleKo: "단의성을 향하여: 사전 학습으로 언어 모델 분해",
            authors: ["Trenton Bricken","Adly Templeton","Joshua Batson","et al."],
            year: 2023,
            venue: "Anthropic Research",
            venueType: "other",
            conferenceUrl: "https://transformer-circuits.pub/2023/monosemantic-features",
            tags: [],
            status: "complete",
            citations: "500+",
          },
          {
            id: "representation-engineering",
            title: "Representation Engineering: A Top-Down Approach to AI Transparency",
            titleKo: "표현 공학: AI 투명성에 대한 탑다운 접근법",
            authors: ["Andy Zou","Long Phan","Sarah Chen","et al."],
            year: 2023,
            venue: "arXiv",
            venueType: "arxiv",
            arxivUrl: "https://arxiv.org/abs/2310.01405",
            tags: [],
            status: "complete",
            citations: "400+",
          },
          {
            id: "weak-to-strong",
            title: "Weak-to-Strong Generalization: Eliciting Strong Capabilities With Weak Supervision",
            titleKo: "약-강 일반화: 약한 감독으로 강한 능력 이끌어내기",
            authors: ["Collin Burns","Haotian Ye","Dan Klein","Jacob Steinhardt"],
            year: 2023,
            venue: "arXiv (OpenAI)",
            venueType: "arxiv",
            arxivUrl: "https://arxiv.org/abs/2312.09390",
            tags: [],
            status: "complete",
            citations: "300+",
          },
        ],
      },
      {
        year: 2024,
        papers: [
          {
            id: "sleeper-agents",
            title: "Sleeper Agents: Training Deceptive LLMs that Persist Through Safety Training",
            titleKo: "슬리퍼 에이전트: 안전 훈련에도 지속되는 기만적 LLM 훈련",
            authors: ["Evan Hubinger","Carson Denison","Jesse Mu","et al."],
            year: 2024,
            venue: "arXiv (Anthropic)",
            venueType: "arxiv",
            arxivUrl: "https://arxiv.org/abs/2401.05566",
            tags: [],
            status: "complete",
            citations: "300+",
          },
        ],
      },
    ],
  },
  {
    id: "optimization",
    titleKo: "최적화·학습이론",
    titleEn: "Optimization & Learning Theory",
    descriptionKo: "SGD, Adam, 수렴 이론, 일반화, 손실 함수 연구",
    descriptionEn: "Research on optimization methods and learning theory",
    color: "blue",
    years: [
      {
        year: 2016,
        papers: [
          {
            id: "gradient-checkpointing",
            title: "Training Deep Nets with Sublinear Memory Cost",
            titleKo: "서브선형 메모리 비용으로 심층 네트워크 학습",
            authors: ["Tianqi Chen","Bing Xu","Chiyuan Zhang","Carlos Guestrin"],
            year: 2016,
            venue: "arXiv",
            venueType: "arxiv",
            arxivUrl: "https://arxiv.org/abs/1604.06174",
            tags: [],
            status: "complete",
            citations: "2,000+",
          },
        ],
      },
      {
        year: 2017,
        papers: [
          {
            id: "adamw",
            title: "Decoupled Weight Decay Regularization",
            titleKo: "분리된 가중치 감쇠 정규화",
            authors: ["Ilya Loshchilov","Frank Hutter"],
            year: 2017,
            venue: "ICLR 2019",
            venueType: "iclr",
            arxivUrl: "https://arxiv.org/abs/1711.05101",
            tags: [],
            status: "complete",
            citations: "10,000+",
          },
          {
            id: "lars",
            title: "Large Batch Training of Convolutional Networks",
            titleKo: "합성곱 네트워크의 대규모 배치 학습",
            authors: ["Yang You","Igor Gitman","Boris Ginsburg"],
            year: 2017,
            venue: "arXiv",
            venueType: "arxiv",
            arxivUrl: "https://arxiv.org/abs/1708.03888",
            tags: [],
            status: "complete",
            citations: "2,000+",
          },
        ],
      },
      {
        year: 2019,
        papers: [
          {
            id: "lottery-ticket",
            title: "The Lottery Ticket Hypothesis: Finding Sparse, Trainable Neural Networks",
            titleKo: "복권 가설: 희소하고 학습 가능한 신경망 찾기",
            authors: ["Jonathan Frankle","Michael Carlin"],
            year: 2019,
            venue: "ICLR 2019",
            venueType: "iclr",
            award: "best-paper",
            arxivUrl: "https://arxiv.org/abs/1803.03635",
            tags: ["theory"],
            status: "complete",
            citations: "5,000+",
          },
          {
            id: "lamb",
            title: "Large Batch Optimization for Deep Learning: Training BERT in 76 minutes",
            titleKo: "딥러닝을 위한 대규모 배치 최적화: BERT 76분 학습",
            authors: ["Yang You","Jing Li","Sashank Reddi","et al."],
            year: 2019,
            venue: "ICLR 2020",
            venueType: "iclr",
            arxivUrl: "https://arxiv.org/abs/1904.00962",
            tags: [],
            status: "complete",
            citations: "1,500+",
          },
        ],
      },
      {
        year: 2020,
        papers: [
          {
            id: "sam-optimizer",
            title: "Sharpness-Aware Minimization for Efficiently Improving Generalization",
            titleKo: "일반화를 효율적으로 개선하기 위한 샤프니스 인식 최소화",
            authors: ["Pierre Foret","Ariel Kleiner","Hossein Mobahi","Behnam Neyshabur"],
            year: 2020,
            venue: "ICLR 2021",
            venueType: "iclr",
            arxivUrl: "https://arxiv.org/abs/2010.01412",
            tags: [],
            status: "complete",
            citations: "3,000+",
          },
        ],
      },
      {
        year: 2022,
        papers: [
          {
            id: "mup",
            title: "Tensor Programs V: Tuning Large Neural Networks via Zero-Shot Hyperparameter Transfer",
            titleKo: "텐서 프로그램 V: 제로샷 하이퍼파라미터 전이를 통한 대규모 신경망 튜닝",
            authors: ["Greg Yang","Edward J. Hu","Igor Babuschkin","et al."],
            year: 2022,
            venue: "arXiv",
            venueType: "arxiv",
            arxivUrl: "https://arxiv.org/abs/2203.03466",
            tags: [],
            status: "complete",
            citations: "500+",
          },
        ],
      },
      {
        year: 2023,
        papers: [
          {
            id: "lion",
            title: "Symbolic Discovery of Optimization Algorithms",
            titleKo: "최적화 알고리즘의 기호적 발견",
            authors: ["Xiangning Chen","Chen Liang","Da Huang","et al."],
            year: 2023,
            venue: "NeurIPS 2023",
            venueType: "neurips",
            arxivUrl: "https://arxiv.org/abs/2302.06675",
            tags: [],
            status: "complete",
            citations: "500+",
          },
          {
            id: "sophia",
            title: "Sophia: A Scalable Stochastic Second-order Optimizer for Language Model Pre-training",
            titleKo: "Sophia: 언어 모델 사전학습을 위한 확장 가능한 확률적 2차 최적화기",
            authors: ["Hong Liu","Zhiyuan Li","David Hall","et al."],
            year: 2023,
            venue: "ICLR 2024",
            venueType: "iclr",
            arxivUrl: "https://arxiv.org/abs/2305.14342",
            tags: [],
            status: "complete",
            citations: "300+",
          },
        ],
      },
      {
        year: 2024,
        papers: [
          {
            id: "schedule-free",
            title: "The Road Less Scheduled",
            titleKo: "스케줄 없는 길",
            authors: ["Aaron Defazio","Xingyu Alice Yang","Harsh Mehta","et al."],
            year: 2024,
            venue: "arXiv (Meta)",
            venueType: "arxiv",
            arxivUrl: "https://arxiv.org/abs/2405.15682",
            tags: [],
            status: "complete",
            citations: "100+",
          },
        ],
      },
    ],
  },
  {
    id: "representation",
    titleKo: "표현 학습",
    titleEn: "Representation Learning",
    descriptionKo: "자기지도학습, 대조학습, 사전학습, 전이학습 연구",
    descriptionEn: "Research on learning useful representations",
    color: "emerald",
    years: [
      {
        year: 2019,
        papers: [
          {
            id: "moco",
            title: "Momentum Contrast for Unsupervised Visual Representation Learning",
            titleKo: "비지도 시각 표현 학습을 위한 모멘텀 대조",
            authors: ["Kaiming He","Haoqi Fan","Yuxin Wu","et al."],
            year: 2019,
            venue: "CVPR 2020",
            venueType: "cvpr",
            arxivUrl: "https://arxiv.org/abs/1911.05722",
            tags: [],
            status: "complete",
            citations: "10,000+",
          },
        ],
      },
      {
        year: 2020,
        papers: [
          {
            id: "simclr",
            title: "A Simple Framework for Contrastive Learning of Visual Representations",
            titleKo: "시각 표현의 대조 학습을 위한 간단한 프레임워크",
            authors: ["Ting Chen","Simon Kornblith","Mohammad Norouzi","Geoffrey Hinton"],
            year: 2020,
            venue: "ICML 2020",
            venueType: "icml",
            arxivUrl: "https://arxiv.org/abs/2002.05709",
            tags: [],
            status: "complete",
            citations: "12,000+",
          },
          {
            id: "byol",
            title: "Bootstrap Your Own Latent: A New Approach to Self-Supervised Learning",
            titleKo: "스스로의 잠재 표현을 부트스트랩하라",
            authors: ["Jean-Bastien Grill","Florian Strub","Florent Altché","et al."],
            year: 2020,
            venue: "NeurIPS 2020",
            venueType: "neurips",
            arxivUrl: "https://arxiv.org/abs/2006.07733",
            tags: [],
            status: "complete",
            citations: "5,000+",
          },
          {
            id: "swav",
            title: "Unsupervised Learning of Visual Features by Contrasting Cluster Assignments",
            titleKo: "클러스터 할당 대조를 통한 비지도 시각 특징 학습",
            authors: ["Mathilde Caron","Ishan Misra","Julien Mairal","et al."],
            year: 2020,
            venue: "NeurIPS 2020",
            venueType: "neurips",
            arxivUrl: "https://arxiv.org/abs/2006.09882",
            tags: [],
            status: "complete",
            citations: "4,000+",
          },
        ],
      },
      {
        year: 2021,
        papers: [
          {
            id: "dino",
            title: "Emerging Properties in Self-Supervised Vision Transformers",
            titleKo: "자기지도 비전 트랜스포머에서 나타나는 특성",
            authors: ["Mathilde Caron","Hugo Touvron","Ishan Misra","et al."],
            year: 2021,
            venue: "ICCV 2021",
            venueType: "iccv",
            arxivUrl: "https://arxiv.org/abs/2104.14294",
            tags: [],
            status: "complete",
            citations: "5,000+",
          },
          {
            id: "beit",
            title: "BEiT: BERT Pre-Training of Image Transformers",
            titleKo: "BEiT: 이미지 트랜스포머의 BERT 사전학습",
            authors: ["Hangbo Bao","Li Dong","Songhao Piao","Furu Wei"],
            year: 2021,
            venue: "ICLR 2022",
            venueType: "iclr",
            arxivUrl: "https://arxiv.org/abs/2106.08254",
            tags: [],
            status: "complete",
            citations: "3,000+",
          },
        ],
      },
      {
        year: 2022,
        papers: [
          {
            id: "mae",
            title: "Masked Autoencoders Are Scalable Vision Learners",
            titleKo: "마스크 오토인코더는 확장 가능한 비전 학습기이다",
            authors: ["Kaiming He","Xinlei Chen","Saining Xie","et al."],
            year: 2022,
            venue: "CVPR 2022",
            venueType: "cvpr",
            arxivUrl: "https://arxiv.org/abs/2111.06377",
            tags: [],
            status: "complete",
            citations: "5,000+",
          },
          {
            id: "data2vec",
            title: "data2vec: A General Framework for Self-supervised Learning in Speech, Vision and Language",
            titleKo: "data2vec: 음성, 비전, 언어에서의 자기지도 학습을 위한 범용 프레임워크",
            authors: ["Alexei Baevski","Wei-Ning Hsu","Qiantong Xu","et al."],
            year: 2022,
            venue: "ICML 2022",
            venueType: "icml",
            arxivUrl: "https://arxiv.org/abs/2202.03555",
            tags: [],
            status: "complete",
            citations: "1,500+",
          },
          {
            id: "vicreg",
            title: "VICReg: Variance-Invariance-Covariance Regularization for Self-Supervised Learning",
            titleKo: "VICReg: 자기지도 학습을 위한 분산-불변성-공분산 정규화",
            authors: ["Adrien Bardes","Jean Ponce","Yann LeCun"],
            year: 2022,
            venue: "ICLR 2022",
            venueType: "iclr",
            arxivUrl: "https://arxiv.org/abs/2105.04906",
            tags: [],
            status: "complete",
            citations: "1,500+",
          },
        ],
      },
      {
        year: 2023,
        papers: [
          {
            id: "dinov2",
            title: "DINOv2: Learning Robust Visual Features without Supervision",
            titleKo: "DINOv2: 감독 없이 강건한 시각 특징 학습",
            authors: ["Maxime Oquab","Timothée Darcet","Théo Moutakanni","et al."],
            year: 2023,
            venue: "arXiv",
            venueType: "arxiv",
            arxivUrl: "https://arxiv.org/abs/2304.07193",
            tags: [],
            status: "complete",
            citations: "2,000+",
          },
        ],
      },
    ],
  },
  {
    id: "science",
    titleKo: "AI for Science",
    titleEn: "AI for Science",
    descriptionKo: "단백질 접힘, 신약, 기후, 수학 증명 등 과학 연구에 AI 적용",
    descriptionEn: "Applying AI to scientific research",
    color: "lime",
    years: [
      {
        year: 2018,
        papers: [
          {
            id: "neural-ode",
            title: "Neural Ordinary Differential Equations",
            titleKo: "신경 상미분방정식",
            authors: ["Ricky T. Q. Chen","Yulia Rubanova","Jesse Bettencourt","David Duvenaud"],
            year: 2018,
            venue: "NeurIPS 2018",
            venueType: "neurips",
            award: "best-paper",
            arxivUrl: "https://arxiv.org/abs/1806.07366",
            tags: [],
            status: "complete",
            citations: "8,000+",
          },
        ],
      },
      {
        year: 2019,
        papers: [
          {
            id: "pinns",
            title: "Physics-informed neural networks: A deep learning framework for solving forward and inverse problems",
            titleKo: "물리 정보 신경망: 정방향 및 역방향 문제를 풀기 위한 딥러닝 프레임워크",
            authors: ["Maziar Raissi","Paris Perdikaris","George Em Karniadakis"],
            year: 2019,
            venue: "Journal of Computational Physics",
            venueType: "other",
            conferenceUrl: "https://doi.org/10.1016/j.jcp.2018.10.045",
            tags: [],
            status: "complete",
            citations: "10,000+",
          },
        ],
      },
      {
        year: 2020,
        papers: [
          {
            id: "alphafold1",
            title: "Improved protein structure prediction using potentials from deep learning",
            titleKo: "딥러닝 포텐셜을 이용한 개선된 단백질 구조 예측",
            authors: ["Andrew W. Senior","Richard Evans","John Jumper","et al."],
            year: 2020,
            venue: "Nature",
            venueType: "nature",
            conferenceUrl: "https://doi.org/10.1038/s41586-019-1923-7",
            tags: [],
            status: "complete",
            citations: "5,000+",
          },
        ],
      },
      {
        year: 2021,
        papers: [
          {
            id: "alphafold2",
            title: "Highly accurate protein structure prediction with AlphaFold",
            titleKo: "AlphaFold를 이용한 고정밀 단백질 구조 예측",
            authors: ["John Jumper","Richard Evans","Alexander Pritzel","et al."],
            year: 2021,
            venue: "Nature",
            venueType: "nature",
            arxivUrl: "https://doi.org/10.1038/s41586-021-03819-2",
            tags: [],
            status: "complete",
            citations: "25,000+",
          },
        ],
      },
      {
        year: 2022,
        papers: [
          {
            id: "esmfold",
            title: "Evolutionary-scale prediction of atomic-level protein structure with a language model",
            titleKo: "언어 모델을 이용한 진화적 규모의 원자 수준 단백질 구조 예측",
            authors: ["Zeming Lin","Halil Akin","Roshan Rao","et al."],
            year: 2022,
            venue: "Science",
            venueType: "science",
            conferenceUrl: "https://doi.org/10.1126/science.ade2574",
            tags: [],
            status: "complete",
            citations: "2,000+",
          },
          {
            id: "fourcastnet",
            title: "FourCastNet: A Global Data-driven High-resolution Weather Forecasting Model",
            titleKo: "FourCastNet: 글로벌 데이터 기반 고해상도 기상 예보 모델",
            authors: ["Jaideep Pathak","Shashank Subramanian","Peter Harrington","et al."],
            year: 2022,
            venue: "arXiv",
            venueType: "arxiv",
            arxivUrl: "https://arxiv.org/abs/2202.11214",
            tags: [],
            status: "complete",
            citations: "800+",
          },
        ],
      },
      {
        year: 2023,
        papers: [
          {
            id: "diffdock",
            title: "DiffDock: Diffusion Steps, Twists, and Turns for Molecular Docking",
            titleKo: "DiffDock: 분자 도킹을 위한 확산 모델",
            authors: ["Gabriele Corso","Hannes Stärk","Bowen Jing","et al."],
            year: 2023,
            venue: "ICLR 2023",
            venueType: "iclr",
            arxivUrl: "https://arxiv.org/abs/2210.01776",
            tags: [],
            status: "complete",
            citations: "700+",
          },
          {
            id: "gnome",
            title: "Scaling deep learning for materials discovery",
            titleKo: "재료 발견을 위한 딥러닝 스케일링",
            authors: ["Amil Merchant","Simon Batzner","Samuel S. Schoenholz","et al."],
            year: 2023,
            venue: "Nature",
            venueType: "nature",
            conferenceUrl: "https://doi.org/10.1038/s41586-023-06735-9",
            tags: [],
            status: "complete",
            citations: "800+",
          },
        ],
      },
      {
        year: 2024,
        papers: [
          {
            id: "alphageometry",
            title: "Solving olympiad geometry without human demonstrations",
            titleKo: "인간 시연 없이 올림피아드 기하 문제 풀기",
            authors: ["Trieu H. Trinh","Yuhuai Wu","Quoc V. Le","et al."],
            year: 2024,
            venue: "Nature",
            venueType: "nature",
            arxivUrl: "https://doi.org/10.1038/s41586-023-06747-5",
            tags: [],
            status: "complete",
            citations: "500+",
          },
          {
            id: "evo",
            title: "Sequence modeling and design from molecular to genome scale with Evo",
            titleKo: "Evo: 분자에서 게놈 규모까지의 시퀀스 모델링과 설계",
            authors: ["Eric Nguyen","Michael Poli","Matthew G. Durrant","et al."],
            year: 2024,
            venue: "Science",
            venueType: "science",
            conferenceUrl: "https://doi.org/10.1126/science.ado9336",
            tags: [],
            status: "complete",
            citations: "200+",
          },
        ],
      },
    ],
  },
  {
    id: "efficient",
    titleKo: "경량화·효율화",
    titleEn: "Efficient AI",
    descriptionKo: "양자화, 프루닝, 증류, NAS, 추론 최적화 연구",
    descriptionEn: "Research on making AI models smaller and faster",
    color: "sky",
    years: [
      {
        year: 2015,
        papers: [
          {
            id: "distillation",
            title: "Distilling the Knowledge in a Neural Network",
            titleKo: "신경망의 지식 증류",
            authors: ["Geoffrey Hinton","Oriol Vinyals","Jeff Dean"],
            year: 2015,
            venue: "NeurIPS 2014 Workshop",
            venueType: "neurips",
            arxivUrl: "https://arxiv.org/abs/1503.02531",
            tags: [],
            status: "complete",
            citations: "15,000+",
          },
        ],
      },
      {
        year: 2021,
        papers: [
          {
            id: "lora",
            title: "LoRA: Low-Rank Adaptation of Large Language Models",
            titleKo: "LoRA: 대규모 언어 모델의 저순위 적응",
            authors: ["Edward J. Hu","Yelong Shen","Phillip Wallis","et al."],
            year: 2021,
            venue: "ICLR 2022",
            venueType: "iclr",
            arxivUrl: "https://arxiv.org/abs/2106.09685",
            tags: [],
            status: "complete",
            citations: "8,000+",
          },
        ],
      },
      {
        year: 2022,
        papers: [
          {
            id: "moe",
            title: "Switch Transformers: Scaling to Trillion Parameter Models with Simple and Efficient Sparsity",
            titleKo: "Switch Transformers: 단순하고 효율적인 희소성으로 조 단위 파라미터 모델로 스케일링",
            authors: ["William Fedus","Barret Zoph","Noam Shazeer"],
            year: 2022,
            venue: "JMLR 2022",
            venueType: "jmlr",
            arxivUrl: "https://arxiv.org/abs/2101.03961",
            tags: [],
            status: "complete",
            citations: "3,000+",
          },
          {
            id: "flash-attention",
            title: "FlashAttention: Fast and Memory-Efficient Exact Attention with IO-Awareness",
            titleKo: "FlashAttention: IO 인식 기반의 빠르고 메모리 효율적인 정확한 어텐션",
            authors: ["Tri Dao","Daniel Y. Fu","Stefano Ermon","et al."],
            year: 2022,
            venue: "NeurIPS 2022",
            venueType: "neurips",
            arxivUrl: "https://arxiv.org/abs/2205.14135",
            tags: [],
            status: "complete",
            citations: "3,000+",
          },
          {
            id: "gptq",
            title: "GPTQ: Accurate Post-Training Quantization for Generative Pre-trained Transformers",
            titleKo: "GPTQ: 생성적 사전학습 트랜스포머의 정확한 사후 학습 양자화",
            authors: ["Elias Frantar","Saleh Ashkboos","Torsten Hoefler","Dan Alistarh"],
            year: 2022,
            venue: "ICLR 2023",
            venueType: "iclr",
            arxivUrl: "https://arxiv.org/abs/2210.17323",
            tags: [],
            status: "complete",
            citations: "1,500+",
          },
        ],
      },
      {
        year: 2023,
        papers: [
          {
            id: "qlora",
            title: "QLoRA: Efficient Finetuning of Quantized LLMs",
            titleKo: "QLoRA: 양자화된 LLM의 효율적 미세 조정",
            authors: ["Tim Dettmers","Artidoro Pagnoni","Ari Holtzman","Luke Zettlemoyer"],
            year: 2023,
            venue: "NeurIPS 2023",
            venueType: "neurips",
            arxivUrl: "https://arxiv.org/abs/2305.14314",
            tags: [],
            status: "complete",
            citations: "3,000+",
          },
          {
            id: "awq",
            title: "AWQ: Activation-aware Weight Quantization for LLM Compression and Acceleration",
            titleKo: "AWQ: LLM 압축과 가속을 위한 활성화 인식 가중치 양자화",
            authors: ["Ji Lin","Jiaming Tang","Haotian Tang","et al."],
            year: 2023,
            venue: "MLSys 2024",
            venueType: "other",
            arxivUrl: "https://arxiv.org/abs/2306.00978",
            tags: [],
            status: "complete",
            citations: "800+",
          },
          {
            id: "speculative-decoding",
            title: "Fast Inference from Transformers via Speculative Decoding",
            titleKo: "추측적 디코딩을 통한 트랜스포머의 빠른 추론",
            authors: ["Yaniv Leviathan","Matan Kalman","Yossi Matias"],
            year: 2023,
            venue: "ICML 2023",
            venueType: "icml",
            arxivUrl: "https://arxiv.org/abs/2211.17192",
            tags: [],
            status: "complete",
            citations: "600+",
          },
          {
            id: "vllm",
            title: "Efficient Memory Management for Large Language Model Serving with PagedAttention",
            titleKo: "PagedAttention을 이용한 대규모 언어 모델 서빙의 효율적 메모리 관리",
            authors: ["Woosuk Kwon","Zhuohan Li","Siyuan Zhuang","et al."],
            year: 2023,
            venue: "SOSP 2023",
            venueType: "other",
            arxivUrl: "https://arxiv.org/abs/2309.06180",
            tags: [],
            status: "complete",
            citations: "1,000+",
          },
          {
            id: "flash-attention-2",
            title: "FlashAttention-2: Faster Attention with Better Parallelism and Work Partitioning",
            titleKo: "FlashAttention-2: 개선된 병렬화와 작업 분할로 더 빠른 어텐션",
            authors: ["Tri Dao"],
            year: 2023,
            venue: "ICLR 2024",
            venueType: "iclr",
            arxivUrl: "https://arxiv.org/abs/2307.08691",
            tags: [],
            status: "complete",
            citations: "800+",
          },
        ],
      },
    ],
  },
  {
    id: "world-models",
    titleKo: "월드 모델",
    titleEn: "World Models",
    descriptionKo: "비디오 예측, 시뮬레이션, 내부 세계 모델 연구",
    descriptionEn: "Research on learning world representations",
    color: "purple",
    years: [
      {
        year: 2018,
        papers: [
          {
            id: "world-models-ha",
            title: "World Models",
            titleKo: "월드 모델",
            authors: ["David Ha","Jürgen Schmidhuber"],
            year: 2018,
            venue: "NeurIPS 2018",
            venueType: "neurips",
            arxivUrl: "https://arxiv.org/abs/1803.10122",
            tags: [],
            status: "complete",
            citations: "3,000+",
          },
        ],
      },
      {
        year: 2020,
        papers: [
          {
            id: "dreamerv1",
            title: "Dream to Control: Learning Behaviors by Latent Imagination",
            titleKo: "꿈꾸며 제어하기: 잠재 상상을 통한 행동 학습",
            authors: ["Danijar Hafner","Timothy Lillicrap","Jimmy Ba","Mohammad Norouzi"],
            year: 2020,
            venue: "ICLR 2020",
            venueType: "iclr",
            arxivUrl: "https://arxiv.org/abs/1912.01603",
            tags: [],
            status: "complete",
            citations: "1,500+",
          },
        ],
      },
      {
        year: 2021,
        papers: [
          {
            id: "dreamerv2",
            title: "Mastering Atari with Discrete World Models",
            titleKo: "이산 월드 모델로 Atari 마스터하기",
            authors: ["Danijar Hafner","Timothy Lillicrap","Mohammad Norouzi","Jimmy Ba"],
            year: 2021,
            venue: "ICLR 2021",
            venueType: "iclr",
            arxivUrl: "https://arxiv.org/abs/2010.02193",
            tags: [],
            status: "complete",
            citations: "1,200+",
          },
        ],
      },
      {
        year: 2022,
        papers: [
          {
            id: "jepa",
            title: "A Path Towards Autonomous Machine Intelligence",
            titleKo: "자율적 기계 지능으로의 경로",
            authors: ["Yann LeCun"],
            year: 2022,
            venue: "OpenReview",
            venueType: "other",
            conferenceUrl: "https://openreview.net/pdf?id=BZ5a1r-kVsf",
            tags: [],
            status: "complete",
            citations: "1,000+",
          },
        ],
      },
      {
        year: 2023,
        papers: [
          {
            id: "iris",
            title: "Transformers are Sample-Efficient World Learners",
            titleKo: "트랜스포머는 샘플 효율적인 월드 학습기이다",
            authors: ["Vincent Micheli","Eloi Alonso","François Fleuret"],
            year: 2023,
            venue: "ICLR 2023",
            venueType: "iclr",
            arxivUrl: "https://arxiv.org/abs/2209.00588",
            tags: [],
            status: "complete",
            citations: "300+",
          },
          {
            id: "unisim",
            title: "UniSim: Learning Interactive Real-World Simulators",
            titleKo: "UniSim: 인터랙티브 실세계 시뮬레이터 학습",
            authors: ["Mengjiao Yang","Yilun Du","Kamyar Ghasemipour","et al."],
            year: 2023,
            venue: "ICLR 2024",
            venueType: "iclr",
            arxivUrl: "https://arxiv.org/abs/2310.06114",
            tags: [],
            status: "complete",
            citations: "200+",
          },
        ],
      },
      {
        year: 2024,
        papers: [
          {
            id: "sora",
            title: "Video generation models as world simulators",
            titleKo: "세계 시뮬레이터로서의 비디오 생성 모델",
            authors: ["OpenAI"],
            year: 2024,
            venue: "OpenAI Technical Report",
            venueType: "other",
            conferenceUrl: "https://openai.com/research/video-generation-models-as-world-simulators",
            tags: [],
            status: "complete",
            citations: "N/A",
          },
          {
            id: "genie",
            title: "Genie: Generative Interactive Environments",
            titleKo: "Genie: 생성적 상호작용 환경",
            authors: ["Jake Bruce","Michael Dennis","Ashley Edwards","et al."],
            year: 2024,
            venue: "ICML 2024",
            venueType: "icml",
            arxivUrl: "https://arxiv.org/abs/2402.15391",
            tags: [],
            status: "complete",
            citations: "200+",
          },
          {
            id: "gamenngen",
            title: "GameNGen: Diffusion Models Are Real-Time Game Engines",
            titleKo: "GameNGen: 확산 모델은 실시간 게임 엔진이다",
            authors: ["Dani Valevski","Yaniv Leviathan","Moab Arar","Shlomi Fruchter"],
            year: 2024,
            venue: "arXiv",
            venueType: "arxiv",
            arxivUrl: "https://arxiv.org/abs/2408.14837",
            tags: [],
            status: "complete",
            citations: "100+",
          },
        ],
      },
    ],
  },
  {
    id: "audio",
    titleKo: "음성·오디오",
    titleEn: "Audio & Speech",
    descriptionKo: "ASR, TTS, 음악 생성, 오디오 이해 연구",
    descriptionEn: "Research on audio and speech processing",
    color: "slate",
    years: [
      {
        year: 2016,
        papers: [
          {
            id: "wavenet",
            title: "WaveNet: A Generative Model for Raw Audio",
            titleKo: "WaveNet: 원시 오디오를 위한 생성 모델",
            authors: ["Aäron van den Oord","Sander Dieleman","Heiga Zen","et al."],
            year: 2016,
            venue: "arXiv",
            venueType: "arxiv",
            arxivUrl: "https://arxiv.org/abs/1609.03499",
            tags: [],
            status: "complete",
            citations: "10,000+",
          },
        ],
      },
      {
        year: 2018,
        papers: [
          {
            id: "tacotron2",
            title: "Natural TTS Synthesis by Conditioning WaveNet on Mel Spectrogram Predictions",
            titleKo: "멜 스펙트로그램 예측 기반 WaveNet 조건부 자연 TTS 합성",
            authors: ["Jonathan Shen","Ruoming Pang","Ron J. Weiss","et al."],
            year: 2018,
            venue: "ICASSP 2018",
            venueType: "other",
            arxivUrl: "https://arxiv.org/abs/1712.05884",
            tags: [],
            status: "complete",
            citations: "5,000+",
          },
        ],
      },
      {
        year: 2021,
        papers: [
          {
            id: "hubert",
            title: "HuBERT: Self-Supervised Speech Representation Learning by Masked Prediction of Hidden Units",
            titleKo: "HuBERT: 은닉 유닛의 마스크 예측을 통한 자기지도 음성 표현 학습",
            authors: ["Wei-Ning Hsu","Benjamin Bolte","Yao-Hung Hubert Tsai","et al."],
            year: 2021,
            venue: "IEEE/ACM TASLP 2021",
            venueType: "other",
            arxivUrl: "https://arxiv.org/abs/2106.07447",
            tags: [],
            status: "complete",
            citations: "3,000+",
          },
          {
            id: "soundstream",
            title: "SoundStream: An End-to-End Neural Audio Codec",
            titleKo: "SoundStream: 엔드투엔드 신경 오디오 코덱",
            authors: ["Neil Zeghidour","Alejandro Luebs","Ahmed Omran","et al."],
            year: 2021,
            venue: "IEEE/ACM TASLP 2022",
            venueType: "other",
            arxivUrl: "https://arxiv.org/abs/2107.03312",
            tags: [],
            status: "complete",
            citations: "1,500+",
          },
        ],
      },
      {
        year: 2022,
        papers: [
          {
            id: "whisper",
            title: "Robust Speech Recognition via Large-Scale Weak Supervision",
            titleKo: "대규모 약한 감독을 통한 강건한 음성 인식",
            authors: ["Alec Radford","Jong Wook Kim","Tao Xu","et al."],
            year: 2022,
            venue: "ICML 2023",
            venueType: "icml",
            arxivUrl: "https://arxiv.org/abs/2212.04356",
            tags: [],
            status: "complete",
            citations: "5,000+",
          },
          {
            id: "audiolm",
            title: "AudioLM: a Language Modeling Approach to Audio Generation",
            titleKo: "AudioLM: 오디오 생성을 위한 언어 모델링 접근법",
            authors: ["Zalán Borsos","Raphaël Marinier","Damien Vincent","et al."],
            year: 2022,
            venue: "IEEE/ACM TASLP 2023",
            venueType: "other",
            arxivUrl: "https://arxiv.org/abs/2209.03143",
            tags: [],
            status: "complete",
            citations: "1,000+",
          },
          {
            id: "encodec",
            title: "High Fidelity Neural Audio Compression",
            titleKo: "고충실도 신경 오디오 압축",
            authors: ["Alexandre Défossez","Jade Copet","Gabriel Synnaeve","Yossi Adi"],
            year: 2022,
            venue: "arXiv",
            venueType: "arxiv",
            arxivUrl: "https://arxiv.org/abs/2210.13438",
            tags: [],
            status: "complete",
            citations: "1,500+",
          },
        ],
      },
      {
        year: 2023,
        papers: [
          {
            id: "vall-e",
            title: "Neural Codec Language Models are Zero-Shot Text to Speech Synthesizers",
            titleKo: "신경 코덱 언어 모델은 제로샷 텍스트 음성 합성기이다",
            authors: ["Chengyi Wang","Sanyuan Chen","Yu Wu","et al."],
            year: 2023,
            venue: "arXiv",
            venueType: "arxiv",
            arxivUrl: "https://arxiv.org/abs/2301.02111",
            tags: [],
            status: "complete",
            citations: "1,000+",
          },
          {
            id: "musiclm",
            title: "MusicLM: Generating Music From Text",
            titleKo: "MusicLM: 텍스트로부터 음악 생성",
            authors: ["Andrea Agostinelli","Timo I. Denk","Zalán Borsos","et al."],
            year: 2023,
            venue: "arXiv",
            venueType: "arxiv",
            arxivUrl: "https://arxiv.org/abs/2301.11325",
            tags: [],
            status: "complete",
            citations: "1,000+",
          },
          {
            id: "bark",
            title: "Bark: Text-Prompted Generative Audio Model",
            titleKo: "Bark: 텍스트 프롬프트 기반 생성 오디오 모델",
            authors: ["Suno AI"],
            year: 2023,
            venue: "GitHub / Suno AI",
            venueType: "other",
            conferenceUrl: "https://github.com/suno-ai/bark",
            tags: [],
            status: "complete",
            citations: "500+",
          },
        ],
      },
    ],
  },
];
