import type { Paper } from "./types";

export const newPapers: Record<string, Paper[]> = {
  "cv": [
    {
      id: "inception",
      title: "Going Deeper with Convolutions",
      titleKo: "더 깊은 합성곱으로: 인셉션 네트워크",
      authors: ["Christian Szegedy", "Wei Liu", "Yangqing Jia", "et al."],
      year: 2015,
      venue: "CVPR 2015",
      venueType: "cvpr",
      award: "best-paper",
      arxivUrl: "https://arxiv.org/abs/1409.4842",
      tags: [],
      status: "complete",
      citations: "40,000+",
    },
    {
      id: "fpn",
      title: "Feature Pyramid Networks for Object Detection",
      titleKo: "객체 검출을 위한 특징 피라미드 네트워크",
      authors: ["Tsung-Yi Lin", "Piotr Dollár", "Ross Girshick", "et al."],
      year: 2017,
      venue: "CVPR 2017",
      venueType: "cvpr",
      arxivUrl: "https://arxiv.org/abs/1612.03144",
      tags: [],
      status: "complete",
      citations: "18,000+",
    },
    {
      id: "efficientnet",
      title: "EfficientNet: Rethinking Model Scaling for Convolutional Neural Networks",
      titleKo: "EfficientNet: 합성곱 신경망의 모델 스케일링 재고",
      authors: ["Mingxing Tan", "Quoc V. Le"],
      year: 2019,
      venue: "ICML 2019",
      venueType: "icml",
      arxivUrl: "https://arxiv.org/abs/1905.11946",
      tags: [],
      status: "complete",
      citations: "20,000+",
    },
    {
      id: "swin-transformer",
      title: "Swin Transformer: Hierarchical Vision Transformer using Shifted Windows",
      titleKo: "Swin Transformer: 이동 윈도우를 이용한 계층적 비전 트랜스포머",
      authors: ["Ze Liu", "Yutong Lin", "Yue Cao", "et al."],
      year: 2021,
      venue: "ICCV 2021",
      venueType: "iccv",
      award: "best-paper",
      arxivUrl: "https://arxiv.org/abs/2103.14030",
      tags: [],
      status: "complete",
      citations: "18,000+",
    },
    {
      id: "convnext",
      title: "A ConvNet for the 2020s",
      titleKo: "2020년대를 위한 합성곱 네트워크",
      authors: ["Zhuang Liu", "Hanzi Mao", "Chao-Yuan Wu", "et al."],
      year: 2022,
      venue: "CVPR 2022",
      venueType: "cvpr",
      arxivUrl: "https://arxiv.org/abs/2201.03545",
      tags: [],
      status: "complete",
      citations: "5,000+",
    },
    {
      id: "dinov2",
      title: "DINOv2: Learning Robust Visual Features without Supervision",
      titleKo: "DINOv2: 감독 없이 강건한 시각적 특징 학습",
      authors: ["Maxime Oquab", "Timothée Darcet", "Théo Moutakanni", "et al."],
      year: 2023,
      venue: "TMLR 2024",
      venueType: "other",
      arxivUrl: "https://arxiv.org/abs/2304.07193",
      tags: [],
      status: "complete",
      citations: "3,000+",
    },
  ],
  "generative": [
    {
      id: "pix2pix",
      title: "Image-to-Image Translation with Conditional Adversarial Networks",
      titleKo: "조건부 적대적 네트워크를 이용한 이미지-이미지 변환",
      authors: ["Phillip Isola", "Jun-Yan Zhu", "Tinghui Zhou", "Alexei A. Efros"],
      year: 2017,
      venue: "CVPR 2017",
      venueType: "cvpr",
      arxivUrl: "https://arxiv.org/abs/1611.07004",
      tags: [],
      status: "complete",
      citations: "20,000+",
    },
    {
      id: "cyclegan",
      title: "Unpaired Image-to-Image Translation using Cycle-Consistent Adversarial Networks",
      titleKo: "순환 일관성 적대적 네트워크를 이용한 비짝 이미지-이미지 변환",
      authors: ["Jun-Yan Zhu", "Taesung Park", "Phillip Isola", "Alexei A. Efros"],
      year: 2017,
      venue: "ICCV 2017",
      venueType: "iccv",
      arxivUrl: "https://arxiv.org/abs/1703.10593",
      tags: [],
      status: "complete",
      citations: "18,000+",
    },
    {
      id: "vqvae2",
      title: "Generating Diverse High-Fidelity Images with VQ-VAE-2",
      titleKo: "VQ-VAE-2를 이용한 다양하고 고품질의 이미지 생성",
      authors: ["Ali Razavi", "Aaron van den Oord", "Oriol Vinyals"],
      year: 2019,
      venue: "NeurIPS 2019",
      venueType: "neurips",
      arxivUrl: "https://arxiv.org/abs/1906.00446",
      tags: [],
      status: "complete",
      citations: "2,000+",
    },
    {
      id: "ddim",
      title: "Denoising Diffusion Implicit Models",
      titleKo: "노이즈 제거 확산 암묵적 모델",
      authors: ["Jiaming Song", "Chenlin Meng", "Stefano Ermon"],
      year: 2020,
      venue: "ICLR 2021",
      venueType: "iclr",
      arxivUrl: "https://arxiv.org/abs/2010.02502",
      tags: [],
      status: "complete",
      citations: "8,000+",
    },
    {
      id: "classifier-free-guidance",
      title: "Classifier-Free Diffusion Guidance",
      titleKo: "분류기 없는 확산 가이던스",
      authors: ["Jonathan Ho", "Tim Salimans"],
      year: 2022,
      venue: "NeurIPS 2022 Workshop",
      venueType: "neurips",
      arxivUrl: "https://arxiv.org/abs/2207.12598",
      tags: [],
      status: "complete",
      citations: "5,000+",
    },
    {
      id: "consistency-models",
      title: "Consistency Models",
      titleKo: "일관성 모델",
      authors: ["Yang Song", "Prafulla Dhariwal", "Mark Chen", "Ilya Sutskever"],
      year: 2023,
      venue: "ICML 2023",
      venueType: "icml",
      arxivUrl: "https://arxiv.org/abs/2303.01469",
      tags: [],
      status: "complete",
      citations: "1,500+",
    },
  ],
};
