import { FoundationPaper } from "./types";

export const foundationPapers: FoundationPaper[] = [
  {
    id: "backpropagation",
    title: "Learning representations by back-propagating errors",
    titleKo: "오류 역전파를 통한 표현 학습",
    authors: ["David E. Rumelhart", "Geoffrey E. Hinton", "Ronald J. Williams"],
    year: 1986,
    venue: "Nature",
    venueType: "nature",
    conferenceUrl: "https://doi.org/10.1038/323533a0",
    tags: ["theory"],
    status: "complete",
    citations: "50,000+",
    era: "~1990s",
  },
  {
    id: "universal-approximation",
    title: "Multilayer feedforward networks are universal approximators",
    titleKo: "다층 순전파 네트워크는 보편적 근사기이다",
    authors: ["Kurt Hornik", "Maxwell Stinchcombe", "Halbert White"],
    year: 1989,
    venue: "Neural Networks",
    venueType: "other",
    conferenceUrl: "https://doi.org/10.1016/0893-6080(89)90020-8",
    tags: ["theory"],
    status: "complete",
    citations: "30,000+",
    era: "~1990s",
  },
  {
    id: "lstm",
    title: "Long Short-Term Memory",
    titleKo: "장단기 기억 네트워크",
    authors: ["Sepp Hochreiter", "Jürgen Schmidhuber"],
    year: 1997,
    venue: "Neural Computation",
    venueType: "other",
    conferenceUrl: "https://doi.org/10.1162/neco.1997.9.8.1735",
    tags: [],
    status: "complete",
    citations: "90,000+",
    era: "~1990s",
  },
  {
    id: "lenet",
    title: "Gradient-Based Learning Applied to Document Recognition",
    titleKo: "문서 인식에 적용된 경사 기반 학습",
    authors: ["Yann LeCun", "Léon Bottou", "Yoshua Bengio", "Patrick Haffner"],
    year: 1998,
    venue: "Proceedings of the IEEE",
    venueType: "other",
    conferenceUrl: "https://doi.org/10.1109/5.726791",
    tags: [],
    status: "complete",
    citations: "50,000+",
    era: "~1990s",
  },
  {
    id: "alexnet",
    title: "ImageNet Classification with Deep Convolutional Neural Networks",
    titleKo: "심층 합성곱 신경망을 이용한 ImageNet 분류",
    authors: ["Alex Krizhevsky", "Ilya Sutskever", "Geoffrey E. Hinton"],
    year: 2012,
    venue: "NeurIPS 2012",
    venueType: "neurips",
    award: "best-paper",
    arxivUrl: "https://papers.nips.cc/paper/2012/hash/c399862d3b9d6b76c8436e924a68c45b-Abstract.html",
    tags: [],
    status: "complete",
    citations: "120,000+",
    era: "2010s-early",
  },
  {
    id: "vae",
    title: "Auto-Encoding Variational Bayes",
    titleKo: "변분 오토인코더",
    authors: ["Diederik P. Kingma", "Max Welling"],
    year: 2013,
    venue: "ICLR 2014",
    venueType: "iclr",
    arxivUrl: "https://arxiv.org/abs/1312.6114",
    tags: ["theory"],
    status: "complete",
    citations: "25,000+",
    era: "2010s-early",
  },
  {
    id: "gan",
    title: "Generative Adversarial Nets",
    titleKo: "생성적 적대 신경망",
    authors: ["Ian Goodfellow", "Jean Pouget-Abadie", "Mehdi Mirza", "Bing Xu", "David Warde-Farley", "Sherjil Ozair", "Aaron Courville", "Yoshua Bengio"],
    year: 2014,
    venue: "NeurIPS 2014",
    venueType: "neurips",
    arxivUrl: "https://arxiv.org/abs/1406.2661",
    tags: [],
    status: "complete",
    citations: "60,000+",
    era: "2010s-early",
  },
  {
    id: "adam",
    title: "Adam: A Method for Stochastic Optimization",
    titleKo: "Adam: 확률적 최적화 방법",
    authors: ["Diederik P. Kingma", "Jimmy Ba"],
    year: 2014,
    venue: "ICLR 2015",
    venueType: "iclr",
    arxivUrl: "https://arxiv.org/abs/1412.6980",
    tags: [],
    status: "complete",
    citations: "200,000+",
    era: "2010s-early",
  },
  {
    id: "seq2seq",
    title: "Sequence to Sequence Learning with Neural Networks",
    titleKo: "신경망을 이용한 시퀀스 투 시퀀스 학습",
    authors: ["Ilya Sutskever", "Oriol Vinyals", "Quoc V. Le"],
    year: 2014,
    venue: "NeurIPS 2014",
    venueType: "neurips",
    arxivUrl: "https://arxiv.org/abs/1409.3215",
    tags: [],
    status: "complete",
    citations: "25,000+",
    era: "2010s-early",
  },
  {
    id: "dropout",
    title: "Dropout: A Simple Way to Prevent Neural Networks from Overfitting",
    titleKo: "드롭아웃: 신경망의 과적합을 방지하는 간단한 방법",
    authors: ["Nitish Srivastava", "Geoffrey Hinton", "Alex Krizhevsky", "Ilya Sutskever", "Ruslan Salakhutdinov"],
    year: 2014,
    venue: "JMLR",
    venueType: "jmlr",
    conferenceUrl: "https://jmlr.org/papers/v15/srivastava14a.html",
    tags: [],
    status: "complete",
    citations: "50,000+",
    era: "2010s-early",
  },
  {
    id: "batch-normalization",
    title: "Batch Normalization: Accelerating Deep Network Training by Reducing Internal Covariate Shift",
    titleKo: "배치 정규화: 내부 공변량 이동 감소를 통한 심층 네트워크 학습 가속",
    authors: ["Sergey Ioffe", "Christian Szegedy"],
    year: 2015,
    venue: "ICML 2015",
    venueType: "icml",
    arxivUrl: "https://arxiv.org/abs/1502.03167",
    tags: [],
    status: "complete",
    citations: "50,000+",
    era: "2010s-mid",
  },
  {
    id: "resnet",
    title: "Deep Residual Learning for Image Recognition",
    titleKo: "이미지 인식을 위한 심층 잔차 학습",
    authors: ["Kaiming He", "Xiangyu Zhang", "Shaoqing Ren", "Jian Sun"],
    year: 2015,
    venue: "CVPR 2016",
    venueType: "cvpr",
    award: "best-paper",
    arxivUrl: "https://arxiv.org/abs/1512.03385",
    tags: [],
    status: "complete",
    citations: "200,000+",
    era: "2010s-mid",
  },
  {
    id: "attention-mechanism",
    title: "Neural Machine Translation by Jointly Learning to Align and Translate",
    titleKo: "정렬과 번역을 동시에 학습하는 신경 기계 번역",
    authors: ["Dzmitry Bahdanau", "Kyunghyun Cho", "Yoshua Bengio"],
    year: 2014,
    venue: "ICLR 2015",
    venueType: "iclr",
    arxivUrl: "https://arxiv.org/abs/1409.0473",
    tags: [],
    status: "complete",
    citations: "40,000+",
    era: "2010s-mid",
  },
  {
    id: "transformer",
    title: "Attention Is All You Need",
    titleKo: "어텐션이 전부다",
    authors: ["Ashish Vaswani", "Noam Shazeer", "Niki Parmar", "Jakob Uszkoreit", "Llion Jones", "Aidan N. Gomez", "Łukasz Kaiser", "Illia Polosukhin"],
    year: 2017,
    venue: "NeurIPS 2017",
    venueType: "neurips",
    arxivUrl: "https://arxiv.org/abs/1706.03762",
    tags: [],
    status: "complete",
    citations: "130,000+",
    era: "2010s-late",
  },
  {
    id: "bert",
    title: "BERT: Pre-training of Deep Bidirectional Transformers for Language Understanding",
    titleKo: "BERT: 언어 이해를 위한 심층 양방향 트랜스포머 사전 학습",
    authors: ["Jacob Devlin", "Ming-Wei Chang", "Kenton Lee", "Kristina Toutanova"],
    year: 2018,
    venue: "NAACL 2019",
    venueType: "naacl",
    award: "best-paper",
    arxivUrl: "https://arxiv.org/abs/1810.04805",
    tags: [],
    status: "complete",
    citations: "100,000+",
    era: "2010s-late",
  },
  {
    id: "gpt",
    title: "Improving Language Understanding by Generative Pre-Training",
    titleKo: "생성적 사전 학습을 통한 언어 이해 향상",
    authors: ["Alec Radford", "Karthik Narasimhan", "Tim Salimans", "Ilya Sutskever"],
    year: 2018,
    venue: "OpenAI",
    venueType: "other",
    conferenceUrl: "https://cdn.openai.com/research-covers/language-unsupervised/language_understanding_paper.pdf",
    tags: [],
    status: "complete",
    citations: "10,000+",
    era: "2010s-late",
  },
  {
    id: "gpt3",
    title: "Language Models are Few-Shot Learners",
    titleKo: "언어 모델은 퓨샷 학습자이다",
    authors: ["Tom Brown", "Benjamin Mann", "Nick Ryder", "Melanie Subbiah", "et al."],
    year: 2020,
    venue: "NeurIPS 2020",
    venueType: "neurips",
    arxivUrl: "https://arxiv.org/abs/2005.14165",
    tags: [],
    status: "complete",
    citations: "40,000+",
    era: "2020s",
  },
  {
    id: "vit",
    title: "An Image is Worth 16x16 Words: Transformers for Image Recognition at Scale",
    titleKo: "이미지는 16x16 단어의 가치가 있다: 대규모 이미지 인식을 위한 트랜스포머",
    authors: ["Alexey Dosovitskiy", "Lucas Beyer", "Alexander Kolesnikov", "et al."],
    year: 2020,
    venue: "ICLR 2021",
    venueType: "iclr",
    arxivUrl: "https://arxiv.org/abs/2010.11929",
    tags: [],
    status: "complete",
    citations: "30,000+",
    era: "2020s",
  },
  {
    id: "ddpm",
    title: "Denoising Diffusion Probabilistic Models",
    titleKo: "잡음 제거 확산 확률 모델",
    authors: ["Jonathan Ho", "Ajay Jain", "Pieter Abbeel"],
    year: 2020,
    venue: "NeurIPS 2020",
    venueType: "neurips",
    arxivUrl: "https://arxiv.org/abs/2006.11239",
    tags: [],
    status: "complete",
    citations: "15,000+",
    era: "2020s",
  },
  {
    id: "scaling-laws",
    title: "Scaling Laws for Neural Language Models",
    titleKo: "신경 언어 모델의 스케일링 법칙",
    authors: ["Jared Kaplan", "Sam McCandlish", "Tom Henighan", "et al."],
    year: 2020,
    venue: "arXiv",
    venueType: "arxiv",
    arxivUrl: "https://arxiv.org/abs/2001.08361",
    tags: ["theory"],
    status: "complete",
    citations: "5,000+",
    era: "2020s",
  },
];
